// Edit these arrays to suit your preferences
// Vehicles that use each type of APS
//dapsLight=["O_MRAP_02_F","O_MRAP_02_gmg_F","O_MRAP_02_hmg_F","O_T_MRAP_02_F","O_T_MRAP_02_gmg_F","O_T_MRAP_02_hmg_F"];
dapsLight=[];
dapsMedium=["O_APC_Tracked_02_cannon_F","O_APC_Wheeled_02_rcws_v2_F","O_T_APC_Tracked_02_cannon_ghex_F","O_T_APC_Wheeled_02_rcws_v2_ghex_F"];
dapsHeavy=[];
dapsTrophyLV=["CUP_B_FV432_Bulldog_GB_D_RWS","CUP_B_FV432_Bulldog_GB_W_RWS","CUP_B_FV432_Bulldog_GB_D","CUP_B_FV432_Bulldog_GB_W","B_MRAP_01_F","B_MRAP_01_gmg_F","B_MRAP_01_hmg_F","B_T_MRAP_01_F","B_T_MRAP_01_gmg_F","B_T_MRAP_01_hmg_F",
"I_MRAP_03_F","I_MRAP_03_gmg_F","I_MRAP_03_hmg_F"];
dapsTrophyMV=[
"CUP_B_FV510_GB_D","CUP_B_FV510_GB_D_SLAT","CUP_B_FV510_GB_W_SLAT","CUP_B_FV510_GB_W",
"CUP_B_MCV80_GB_D","CUP_B_MCV80_GB_D_SLAT","CUP_B_MCV80_GB_W_SLAT","CUP_B_MCV80_GB_W",
"B_APC_Wheeled_01_cannon_F","B_T_APC_Wheeled_01_cannon_F",
"B_AFV_Wheeled_01_cannon_F","B_AFV_Wheeled_01_up_cannon_F","B_T_AFV_Wheeled_01_cannon_F","B_T_AFV_Wheeled_01_up_cannon_F",
"I_APC_Wheeled_03_cannon_F","I_APC_tracked_03_cannon_F",
"B_APC_Tracked_01_rcws_F",
"B_T_APC_Tracked_01_rcws_F",
"RHS_M2A2_wd",
"RHS_M2A2",
"RHS_M2A2_BUSKI_WD",
"RHS_M2A2_BUSKI",
"RHS_M2A3_wd",
"RHS_M2A3",
"RHS_M2A3_BUSKI_wd",
"RHS_M2A3_BUSKI",
"RHS_M2A3_BUSKIII_wd",
"RHS_M2A3_BUSKIII",
"RHS_M6_wd",
"RHS_M6"
];
dapsTrophyHV=[
"B_MBT_01_cannon_F",
"B_T_MBT_01_cannon_F",
"B_MBT_01_TUSK_F",
"B_T_MBT_01_TUSK_F",
"rhsusf_m1a1aimwd_usarmy",
"rhsusf_m1a1aimd_usarmy",
"rhsusf_m1a1aim_tuski_wd",
"rhsusf_m1a1aim_tuski_d",
"rhsusf_m1a1fep_wd",
"rhsusf_m1a1fep_d",
"rhsusf_m1a2sep1wd_usarmy",
"rhsusf_m1a2sep1d_usarmy",
"rhsusf_m1a2sep1tuskiwd_usarmy",
"rhsusf_m1a2sep1tuskid_usarmy",
"rhsusf_m1a2sep1tuskiiwd_usarmy",
"rhsusf_m1a2sep1tuskiid_usarmy",
"MEC_IDF_Merkava",
"MEC_IDF_Merkava4"
];
dapsTrophyHVe=[];
dapsArena=[];
dapsDrozd=[];
dapsDrozd2=["O_MBT_02_cannon_F","O_T_MBT_02_cannon_ghex_F"];
dapsAfganit=[];
dapsAfganitE=["O_MBT_04_cannon_F","O_MBT_04_command_F","O_T_MBT_04_cannon_F","O_T_MBT_04_command_F"];
dapsDazzler=["CUP_O_T90_RU","MEC_SAA_T72","MEC_SAA_T90"];
dapsIronFist=[];
dapsAMAP=["I_MBT_03_cannon_F"];