//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 172.142223 on Stable branch
// Generated with ALiVE version 1.3.6.1706261
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class RUS {
        displayName = "Russian Spetznaz";
        side = 0;
        flag = "\ca\data\flag_rus_co.paa";
        icon = "\ca\data\flag_rus_co.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class RUS {
            name = "Russian Spetznaz";

            class Infantry {
                name = "Infantry";

                class rus_infantry_sentry {
                    name = "Sentry";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Grenadier_01";
                    };
                };

                class rus_infantry_assault_team {
                    name = "Assault Team";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_Fireteam_Leader_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_01";
                    };
                };

                class rus_infantry_fireteam {
                    name = "Fireteam";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_Fireteam_Leader_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_AT_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_01";
                    };
                };

                class rus_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Marksman_VSS_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Medic_01";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_AT_01";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Grenadier_01";
                    };
                    class Unit6 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class rus_specops_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_Sniper_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Spotter_01";
                    };
                };

                class rus_specops_recon_element {
                    name = "Recon Element";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_Recon_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Marksman_VSS_01";
                    };
                };

                class rus_specops_sso_sniper_team {
                    name = "SSO Sniper Team";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_SSO_Sniper_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Spotter_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

                class rus_support_sso_sentry {
                    name = "SSO Sentry";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_SSO_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Grenadier_01";
                    };
                };

                class rus_support_sso_assault_team {
                    name = "SSO Assault Team";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_SSO_Fireteam_Leader_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Autorifleman_01";
                    };
                };

                class rus_support_sso_fireteam {
                    name = "SSO Fireteam";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_SSO_Fireteam_Leader_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Rifleman_AT_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Rifleman_01";
                    };
                };

                class rus_support_sso_squad {
                    name = "SSO Squad";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_SSO_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Medic_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Marksman_01";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Grenadier_01";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Rifleman_AT_01";
                    };
                    class Unit6 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_SSO_Rifleman_01";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

                class rus_armored_t72_bm {
                    name = "T-72 BM";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\n_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_T80_BV_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

                class rus_air_hunter_killers {
                    name = "Hunter-Killers";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_Mi_24P_Hind_01";
                    };
                    class Unit1 {
                        position[] = { 22 , -26 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Mi_24P_Hind_01";
                    };
                };

                class rus_air_airbourne_spetznaz {
                    name = "Airbourne Spetznaz";
                    side = 0;
                    faction = "RUS";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_RUS_Mi_24P_Hind_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Medic_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_AT_01";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Marksman_VSS_01";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Grenadier_01";
                    };
                    class Unit6 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Autorifleman_01";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = { -20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_RUS_Rifleman_01";
                    };
                };

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_Soldier_TL_F;
    class I_Soldier_TL_F_OCimport_01 : I_Soldier_TL_F { scope = 0; class EventHandlers; };
    class I_Soldier_TL_F_OCimport_02 : I_Soldier_TL_F_OCimport_01 { class EventHandlers; };

    class I_soldier_F;
    class I_soldier_F_OCimport_01 : I_soldier_F { scope = 0; class EventHandlers; };
    class I_soldier_F_OCimport_02 : I_soldier_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_AR_F;
    class I_Soldier_AR_F_OCimport_01 : I_Soldier_AR_F { scope = 0; class EventHandlers; };
    class I_Soldier_AR_F_OCimport_02 : I_Soldier_AR_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_GL_F;
    class I_Soldier_GL_F_OCimport_01 : I_Soldier_GL_F { scope = 0; class EventHandlers; };
    class I_Soldier_GL_F_OCimport_02 : I_Soldier_GL_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_M_F;
    class I_Soldier_M_F_OCimport_01 : I_Soldier_M_F { scope = 0; class EventHandlers; };
    class I_Soldier_M_F_OCimport_02 : I_Soldier_M_F_OCimport_01 { class EventHandlers; };

    class I_Spotter_F;
    class I_Spotter_F_OCimport_01 : I_Spotter_F { scope = 0; class EventHandlers; };
    class I_Spotter_F_OCimport_02 : I_Spotter_F_OCimport_01 { class EventHandlers; };

    class I_Soldier_SL_F;
    class I_Soldier_SL_F_OCimport_01 : I_Soldier_SL_F { scope = 0; class EventHandlers; };
    class I_Soldier_SL_F_OCimport_02 : I_Soldier_SL_F_OCimport_01 { class EventHandlers; };

    class RHS_Ka52_UPK23_vvs;
    class RHS_Ka52_UPK23_vvs_OCimport_01 : RHS_Ka52_UPK23_vvs { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Ka52_UPK23_vvs_OCimport_02 : RHS_Ka52_UPK23_vvs_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_mvd_izlom_rifleman_LAT;
    class rhs_mvd_izlom_rifleman_LAT_OCimport_01 : rhs_mvd_izlom_rifleman_LAT { scope = 0; class EventHandlers; };
    class rhs_mvd_izlom_rifleman_LAT_OCimport_02 : rhs_mvd_izlom_rifleman_LAT_OCimport_01 { class EventHandlers; };

    class I_Sniper_F;
    class I_Sniper_F_OCimport_01 : I_Sniper_F { scope = 0; class EventHandlers; };
    class I_Sniper_F_OCimport_02 : I_Sniper_F_OCimport_01 { class EventHandlers; };

    class rhs_t80bv;
    class rhs_t80bv_OCimport_01 : rhs_t80bv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_t80bv_OCimport_02 : rhs_t80bv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class RHS_Mi24P_CAS_vdv;
    class RHS_Mi24P_CAS_vdv_OCimport_01 : RHS_Mi24P_CAS_vdv { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Mi24P_CAS_vdv_OCimport_02 : RHS_Mi24P_CAS_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class RHS_AGS30_TriPod_VDV;
    class RHS_AGS30_TriPod_VDV_OCimport_01 : RHS_AGS30_TriPod_VDV { scope = 0; class EventHandlers; class Turrets; };
    class RHS_AGS30_TriPod_VDV_OCimport_02 : RHS_AGS30_TriPod_VDV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhs_KORD_MSV;
    class rhs_KORD_MSV_OCimport_01 : rhs_KORD_MSV { scope = 0; class EventHandlers; class Turrets; };
    class rhs_KORD_MSV_OCimport_02 : rhs_KORD_MSV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class RHS_Mi8mt_vdv;
    class RHS_Mi8mt_vdv_OCimport_01 : RHS_Mi8mt_vdv { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Mi8mt_vdv_OCimport_02 : RHS_Mi8mt_vdv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class BackTurret;
        };
    };

    class rhs_bmp3mera_msv;
    class rhs_bmp3mera_msv_OCimport_01 : rhs_bmp3mera_msv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_bmp3mera_msv_OCimport_02 : rhs_bmp3mera_msv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class GPMGTurret1;
            class GPMGTurret2;
        };
    };

    class I_RUS_Medic_01;
    class I_RUS_Medic_01_OCimport_01 : I_RUS_Medic_01 { scope = 0; class EventHandlers; };
    class I_RUS_Medic_01_OCimport_02 : I_RUS_Medic_01_OCimport_01 { class EventHandlers; };

    class I_RUS_Squad_Leader_01;
    class I_RUS_Squad_Leader_01_OCimport_01 : I_RUS_Squad_Leader_01 { scope = 0; class EventHandlers; };
    class I_RUS_Squad_Leader_01_OCimport_02 : I_RUS_Squad_Leader_01_OCimport_01 { class EventHandlers; };

    class O_crew_F;
    class O_crew_F_OCimport_01 : O_crew_F { scope = 0; class EventHandlers; };
    class O_crew_F_OCimport_02 : O_crew_F_OCimport_01 { class EventHandlers; };

    class rhs_tigr_sts_vv;
    class rhs_tigr_sts_vv_OCimport_01 : rhs_tigr_sts_vv { scope = 0; class EventHandlers; class Turrets; };
    class rhs_tigr_sts_vv_OCimport_02 : rhs_tigr_sts_vv_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class AGS_Turret;
        };
    };

    class I_medic_F;
    class I_medic_F_OCimport_01 : I_medic_F { scope = 0; class EventHandlers; };
    class I_medic_F_OCimport_02 : I_medic_F_OCimport_01 { class EventHandlers; };


    class O_RUS_Fireteam_Leader_01 : I_Soldier_TL_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Fireteam Leader";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74mr','rhs_acc_dtk','rhs_acc_perst3_2dp_light_h','rhsusf_acc_SpecterDR',['rhs_30Rnd_545x39_AK',30],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf_R',[['FirstAidKit',6]]],['VSM_FAPC_Breacher_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_30Rnd_545x39_AK',10,30],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1],['rhs_mag_fakels',2,1]]],[],'rhs_6b7_1m_bala2_olive','',['Binocular','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Rifleman_01 : I_soldier_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74m_npz','rhs_acc_dtk','','rhsusf_acc_eotech_xps3',['rhs_30Rnd_545x39_AK',30],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf',[['FirstAidKit',6]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_30Rnd_545x39_AK',10,30],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1]]],[],'Surpat_Helmet','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Autorifleman_01 : I_Soldier_AR_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_pkp','','','rhs_acc_1p78',['rhs_100Rnd_762x54mmR',100],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf_R',[['FirstAidKit',6]]],['VSM_FAPC_MG_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_100Rnd_762x54mmR',3,100],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1]]],[],'rhs_altyn_novisor_ess_bala','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Grenadier_01 : I_Soldier_GL_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74m_gp25_npz','rhs_acc_dtk','','rhsusf_acc_eotech_xps3',['rhs_30Rnd_545x39_AK',30],['rhs_VOG25',1],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf_TG',[['FirstAidKit',5]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_30Rnd_545x39_AK',10,30],['rhs_VOG25',9,1],['rhs_VG40OP_white',1,1],['rhs_mag_rgo',1,1],['rhs_mag_rdg2_white',2,1]]],[],'rhsusf_opscore_rg_cover','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Marksman_VSS_01 : I_Soldier_M_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman (VSS)";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_vss_grip','','rhs_acc_perst1ik_ris','rhs_acc_pso1m21',['rhs_10rnd_9x39mm_SP5',10],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf',[['FirstAidKit',6]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_10rnd_9x39mm_SP5',10,10],['rhs_mag_9x19_17',4,17],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1],['rhs_mag_nspn_green',1,1]]],[],'Surpat_Cap','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Recon_01 : I_Spotter_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Recon";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_NATO_sniper" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_aks74un','rhs_acc_pbs4','','',['rhs_30Rnd_545x39_AK',30],[],''],[],['rhs_weap_tr8','','','',[],[],''],['Surpat_Camo_Unf',[['FirstAidKit',6]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_30Rnd_545x39_7U1_AK',12,30],['rhs_mag_rgn',2,1],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1]]],[],'rhsusf_opscore_rg_cover','VSM_Balaclava2_OD_Peltor_Goggles',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Squad_Leader_01 : I_Soldier_SL_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak103_zenitco01_b33','rhs_acc_dtk3','rhs_acc_perst3','rhsusf_acc_SpecterDR_A',['rhs_30Rnd_762x39mm',30],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf',[['FirstAidKit',6]]],['VSM_FAPC_Breacher_OGA_OD',[['I_IR_Grenade',1,1],['rhs_30Rnd_762x39mm',10,30],['rhs_mag_9x19_17',4,17],['rhs_mag_rgn',2,1],['rhs_mag_rdg2_white',1,1]]],[],'VSM_Black_OPS_2','G_Aviator',['rhs_pdu4','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Ka_52_Alligator_01 : RHS_Ka52_UPK23_vvs_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ka-52 'Alligator'";
        side = 0;
        faction = "RUS";
        crew = "rhs_pilot_combat_heli";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Rifleman_AT_01 : rhs_mvd_izlom_rifleman_LAT_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "Head_Russian" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74m_zenitco01','rhs_acc_dtk','rhs_acc_perst3','',['rhs_30Rnd_545x39_AK',30],[],'rhs_acc_grip_ffg2'],['rhs_weap_rpg26','','','',['rhs_rpg26_mag',1],[],''],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf_R',[['FirstAidKit',4],['rhs_1PN138',1]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_30Rnd_545x39_AK',10,30],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1]]],[],'rhs_6b7_1m_bala1_olive','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Sniper_01 : I_Sniper_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_NATO_sniper" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_t5000','','','rhs_acc_dh520x56',['rhs_5Rnd_338lapua_t5000',5],[],'rhs_acc_harris_swivel'],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf_Ghillie',[['FirstAidKit',5],['SmokeShell',2,1]]],['V_TacChestrig_grn_F',[['I_IR_Grenade',1,1],['rhs_5Rnd_338lapua_t5000',12,5],['rhs_mag_9x19_17',4,17],['rhs_mag_rgn',2,1],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1]]],[],'Surpat_Boonie_HS','',['rhs_pdu4','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Spotter_01 : I_Spotter_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Spotter";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Greek" , "LanguageGRE_F" , "G_NATO_sniper" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74mr','rhs_acc_tgpa','rhs_acc_perst3','rhsusf_acc_eotech_xps3',['rhs_30Rnd_545x39_AK',30],[],'rhs_acc_grip_rk6'],[],['rhs_weap_rsp30_green','','','',[],[],''],['Surpat_Camo_Unf_Ghillie',[['FirstAidKit',5],['SmokeShell',2,1]]],['V_TacChestrig_grn_F',[['I_IR_Grenade',2,1],['rhs_30Rnd_545x39_AK',10,30],['rhs_mag_rgn',1,1],['rhs_mag_rdg2_white',2,1]]],[],'Surpat_Boonie_HS','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_T80_BV_01 : rhs_t80bv_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "T-80 BV";
        side = 0;
        faction = "RUS";
        crew = "O_RUS_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_RUS_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_RUS_Mi_24P_Hind_01 : RHS_Mi24P_CAS_vdv_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mi-24P Hind";
        side = 0;
        faction = "RUS";
        crew = "O_RUS_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_RUS_Crewman_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_AGS_30_01 : RHS_AGS30_TriPod_VDV_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "AGS-30";
        side = 0;
        faction = "RUS";
        crew = "I_RUS_Rifleman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_KORD_01 : rhs_KORD_MSV_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "KORD";
        side = 0;
        faction = "RUS";
        crew = "I_RUS_Rifleman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Mi_8Hip_01 : RHS_Mi8mt_vdv_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mi-8 Hip";
        side = 0;
        faction = "RUS";
        crew = "O_RUS_Crewman_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "O_RUS_Crewman_01"; };
            class MainTurret : MainTurret { gunnerType = "O_RUS_Crewman_01"; };
            class BackTurret : BackTurret { gunnerType = "O_RUS_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_BMP_3Up_Armored_01 : rhs_bmp3mera_msv_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "BMP-3 (Up-Armored)";
        side = 0;
        faction = "RUS";
        crew = "I_RUS_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_RUS_Crewman_01"; };
            class GPMGTurret1 : GPMGTurret1 { gunnerType = "rhs_msv_rifleman"; };
            class GPMGTurret2 : GPMGTurret2 { gunnerType = "rhs_msv_rifleman"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Rifleman_01 : O_RUS_Rifleman_01 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Rifleman";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74m_desert_npz','rhs_acc_dtk','','rhsusf_acc_eotech_xps3',['rhs_30Rnd_545x39_AK',30],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['VSM_Multicam_Camo',[['FirstAidKit',6]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1],['rhs_30Rnd_545x39_AK',10,30]]],[],'rhsusf_opscore_rg_cover_pelt','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Autorifleman_01 : O_RUS_Autorifleman_01 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Autorifleman";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_pkp','','','rhs_acc_1p78',['rhs_100Rnd_762x54mmR',100],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['VSM_Multicam_tan_shirt_Camo_SS',[['FirstAidKit',6]]],['VSM_FAPC_MG_Multicam',[['rhs_mag_9x19_17',4,17],['rhs_100Rnd_762x54mmR',3,100],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1]]],[],'rhsusf_opscore_coy_cover_pelt','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Grenadier_01 : O_RUS_Grenadier_01 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Grenadier";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74mr_gp25','rhs_acc_dtk','','rhsusf_acc_compm4',['rhs_30Rnd_545x39_AK',30],['rhs_VOG25',1],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['VSM_Multicam_casual_Camo',[['FirstAidKit',6],['rhs_30Rnd_545x39_AK',1,30]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_VOG25',10,1],['rhs_VG40OP_white',1,1],['rhs_mag_rgo',1,1],['rhs_mag_rdg2_white',2,1],['rhs_30Rnd_545x39_AK',10,30]]],[],'rhsusf_opscore_coy_cover_pelt','',['Binocular','','','',[],[],''],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Fireteam_Leader_01 : O_RUS_Fireteam_Leader_01 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Fireteam Leader";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak103_zenitco01','rhs_acc_dtk','','rhs_acc_pkas',['rhs_30Rnd_762x39mm',30],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['VSM_Multicam_Camo',[['FirstAidKit',6]]],['VSM_FAPC_Breacher_Multicam',[['rhs_mag_9x19_17',4,17],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1],['rhs_mag_fakels',2,1],['rhs_30Rnd_762x39mm',8,30]]],[],'rhsusf_opscore_mc_cover_pelt_cam','VSM_balaclava2_Black',['Binocular','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Medic_01 : I_RUS_Medic_01_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Medic";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak103_zenitco01_b33','rhs_acc_dtk','rhs_acc_perst3','rhs_acc_rakursPM',['rhs_30Rnd_762x39mm',30],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['VSM_Multicam_Crye_Camo',[['FirstAidKit',6]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_30Rnd_762x39mm',10,30],['rhs_mag_9x19_17',4,17],['rhs_mag_rgo',2,1],['rhs_mag_nspn_green',1,1],['rhs_mag_fakel',2,1]]],['I_Fieldpack_oli_Medic',[['Medikit',1],['FirstAidKit',10]]],'VSM_Mich2000_2_CamoSprayTAN','G_Combat',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Marksman_01 : O_RUS_Marksman_VSS_01 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Marksman";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_svds','rhs_acc_tgpv','','rhs_acc_pso1m21',['rhs_10Rnd_762x54mmR_7N1',10],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['VSM_Multicam_Crye_Camo',[['FirstAidKit',6],['rhs_mag_rgn',2,1]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1],['rhs_mag_nspn_green',1,1],['rhs_10Rnd_762x54mmR_7N1',12,10]]],[],'rhsusf_opscore_mc_pelt_nsw','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Rifleman_AT_01 : O_RUS_Rifleman_AT_01 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Rifleman (AT)";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "Head_Russian" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74m_zenitco01','rhs_acc_dtk','rhs_acc_perst3','',['rhs_30Rnd_545x39_AK',30],[],'rhs_acc_grip_ffg2'],['rhs_weap_rpg26','','','',['rhs_rpg26_mag',1],[],''],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['VSM_Multicam_tan_pants_Camo_SS',[['FirstAidKit',4],['rhs_1PN138',1]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_mag_9x19_17',4,17],['rhs_30Rnd_545x39_AK',10,30],['rhs_mag_rgo',2,1],['rhs_mag_rdg2_white',2,1]]],[],'rhs_6b7_1m_bala2_olive','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Squad_Leader_01 : I_RUS_Squad_Leader_01_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Squad Leader";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak103_zenitco01_b33','rhs_acc_dtk3','rhs_acc_perst3','rhsusf_acc_SpecterDR_A',['rhs_30Rnd_762x39mm',30],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['VSM_Multicam_Crye_Camo',[['FirstAidKit',6]]],['VSM_FAPC_Breacher_OGA_OD',[['I_IR_Grenade',1,1],['rhs_30Rnd_762x39mm',10,30],['rhs_mag_9x19_17',4,17],['rhs_mag_rgn',2,1],['rhs_mag_rdg2_white',1,1]]],[],'VSM_Black_OPS_2','G_Shades_Green',['rhs_pdu4','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Sniper_01 : O_RUS_Sniper_01 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Sniper";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_NATO_sniper" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_t5000','','','rhs_acc_dh520x56',['rhs_5Rnd_338lapua_t5000',5],[],'rhs_acc_harris_swivel'],[],['rhsusf_weap_glock17g4','','','',['rhsusf_mag_17Rnd_9x19_JHP',17],[],''],['VSM_Multicam_Crye_Camo',[['FirstAidKit',5],['SmokeShell',2,1],['rhsusf_mag_17Rnd_9x19_JHP',3,17]]],['VSM_CarrierRig_Operator_OGA',[['I_IR_Grenade',1,1],['rhs_5Rnd_338lapua_t5000',12,5],['rhs_mag_rgn',2,1],['rhs_mag_rdg2_white',2,1],['rhs_mag_rdg2_black',1,1]]],[],'rhsusf_mich_bare_norotos_arc_tan','',['rhs_pdu4','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_SSO_Spotter_01 : O_RUS_Spotter_01 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "SSO Spotter";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Greek" , "LanguageGRE_F" , "G_NATO_sniper" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak74mr','rhs_acc_tgpa','rhs_acc_perst3','rhsusf_acc_SpecterDR',['rhs_30Rnd_545x39_AK',30],[],'rhs_acc_grip_rk6'],[],['rhsusf_weap_glock17g4','','','',['rhsusf_mag_17Rnd_9x19_JHP',17],[],''],['VSM_Multicam_Crye_SS_Camo',[['FirstAidKit',5],['SmokeShell',2,1],['rhsusf_mag_17Rnd_9x19_JHP',3,17]]],['VSM_CarrierRig_Operator_OGA',[['I_IR_Grenade',2,1],['rhs_30Rnd_545x39_AK',10,30],['rhs_mag_rgn',1,1],['rhs_mag_rdg2_white',2,1]]],[],'VSM_Bowman_cap_balaclava_Tan','',['Rangefinder','','','',[],[],''],['ItemMap','ItemGPS','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Crewman_01 : O_crew_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_IRAN_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_aks74u','rhs_acc_pgs64_74u','','',['rhs_30Rnd_545x39_AK',30],[],''],[],['rhs_weap_pya','','','',[],[],''],['rhs_uniform_emr_patchless',[['FirstAidKit',5]]],['rhs_vest_commander',[['SmokeShell',1,1],['rhs_30Rnd_545x39_AK',3,30]]],[],'rhs_tsh4_ess_bala','',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_GAZ_Armed_01 : rhs_tigr_sts_vv_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "GAZ (Armed)";
        side = 0;
        faction = "RUS";
        crew = "O_RUS_Rifleman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_RUS_Rifleman_01"; };
            class AGS_Turret : AGS_Turret { gunnerType = "O_RUS_Fireteam_Leader_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_RUS_Medic_01 : I_medic_F_OCimport_02 {
        author = "jarrad96";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "RUS";

        identityTypes[] = { "Head_Euro" , "LanguageRus" , "G_HAF_default" };


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_unit = _this select 0;_onSpawn = {_unit = _this select 0;_unit setUnitLoadout [['rhs_weap_ak103_zenitco01_b33','rhs_acc_dtk','rhs_acc_perst3','rhs_acc_rakursPM',['rhs_30Rnd_762x39mm',30],[],''],[],['rhs_weap_pya','','','',['rhs_mag_9x19_17',17],[],''],['Surpat_Camo_Unf',[['FirstAidKit',6]]],['VSM_FAPC_Operator_OGA_OD',[['rhs_30Rnd_762x39mm',10,30],['rhs_mag_9x19_17',4,17],['rhs_mag_rgo',2,1],['rhs_mag_nspn_green',1,1],['rhs_mag_fakel',2,1]]],['I_Fieldpack_oli_Medic',[['Medikit',1],['FirstAidKit',10]]],'VSM_Mich2000_2_CamoSprayOD','VSM_balaclava2_Black',[],['ItemMap','','ItemRadio','ItemCompass','ItemWatch','rhs_1PN138']];reload _unit;};[_unit] call _onSpawn;_unit addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};