missionNamespace setVariable["r0ed_SurvivableCrashes_Initialized", true];

if(missionNamespace getVariable ["r0ed_SurvivableCrashes_Initialized", false]) exitWith {};

[	bnb_e_sc_enable,  // Mod Enabled
	true,   //VFX
	true,   //SFX
	true,   // Exag FX
	"AUTO", // Med Sys
	bnb_e_sc_damage,      // dmg Multi
	["Air"],// Veh whitelist
	{},     // On Crash Code
	{},     // crew Post Crash code
	{       // veh post crash code
		params["_veh"];
		sleep (40 + random 40);
		_veh allowDamage true;
		_veh setDamage 1;
	}
] call compile preprocessFileLineNumbers "\r0ed_SurvivableCrashes\functions\init\init_survivableCrashes.sqf";

//------------------------- 2BNB AOR 1 Kits --------------------------------------
["2BNB IC/2IC AOR1",[["SMA_HK416GL","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552_3XDOWN",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["VSM_AOR1_Crye_SS_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_AOR1",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5],["ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30],["ACE_30Rnd_556x45_Stanag_Mk262_mag",5,30]]],["tfw_ilbe_dd_d",[["ACE_30Rnd_556x45_Stanag_Mk262_mag",6,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",3,1],["SmokeShell",5,1],["CUP_1Rnd_HE_M203",10,1],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_SmokeRed_Grenade_shell",5,1],["SmokeShellOrange",2,1],["SmokeShellPurple",2,1],["SmokeShellRed",2,1],["SmokeShellYellow",2,1]]],"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_tan_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
["2BNB AT AOR1",[["SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],["launch_MRAWS_sand_rail_F","","","",["MRAWS_HEAT_F",1],[],""],[],["VSM_AOR1_Crye_SS_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_AOR1",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5],["ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30]]],["VSM_AOR1_Backpack_Kitbag",[["ACE_30Rnd_556x45_Stanag_Mk262_mag",4,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShell",4,1]]],"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_tan_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
["2BNB LMG AOR1",[["CUP_lmg_MG3_rail","","","CUP_optic_HoloBlack",["CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",120],[],""],[],[],["VSM_AOR1_Crye_SS_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_AOR1",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5]]],["VSM_AOR1_Backpack_Kitbag",[["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShell",4,1],["CUP_120Rnd_TE4_LRT4_Green_Tracer_762x51_Belt_M",3,120]]],"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
["2BNB Marksman AOR1",[["SMA_HK417_16in","SMA_supp_762","SMA_SFPEQ_HK417TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_20Rnd_762x51mm_M80A1_EPR_IR",20],[],"bipod_01_F_blk"],[],[],["VSM_AOR1_Crye_SS_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_AOR1",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5],["SMA_20Rnd_762x51mm_M80A1_EPR_IR",7,20]]],["VSM_AOR1_Backpack_Kitbag",[["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShell",4,1],["SMA_20Rnd_762x51mm_M80A1_EPR_IR",7,20],["20Rnd_762x51_Mag",7,20]]],"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_tan_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
["2BNB Rifleman AOR1",[["SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["VSM_AOR1_Crye_SS_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_AOR1",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5]]],["VSM_AOR1_Backpack_Kitbag",[["ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30],["ACE_30Rnd_556x45_Stanag_Mk262_mag",8,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShell",4,1]]],"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_tan_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
//-------------------------------------------------------------------------------

//-------------------------- 2BNB M81 Kits ------------------------------------
["2BNB IC/2IC M81",[["SMA_HK416GL","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552_3XDOWN",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["VSM_M81_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_M81",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5],["ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30],["ACE_30Rnd_556x45_Stanag_Mk262_mag",5,30]]],["VSM_M81_Backpack_Kitbag",[["ACE_30Rnd_556x45_Stanag_Mk262_mag",6,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",3,1],["SmokeShell",5,1],["CUP_1Rnd_HE_M203",10,1],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_SmokeRed_Grenade_shell",5,1],["SmokeShellOrange",2,1],["SmokeShellPurple",2,1],["SmokeShellRed",2,1],["SmokeShellYellow",2,1]]],"VSM_Mich2000_2_M81","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
["2BNB AT M81",[["SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],["launch_MRAWS_green_rail_F","","","",["MRAWS_HEAT_F",1],[],""],[],["VSM_M81_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_M81",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5],["ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30]]],["VSM_M81_Backpack_Kitbag",[["ACE_30Rnd_556x45_Stanag_Mk262_mag",4,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShell",4,1],["MRAWS_HEAT_F",3,1]]],"VSM_Mich2000_2_M81","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
["2BNB LMG M81",[["CUP_lmg_MG3_rail","","","CUP_optic_HoloBlack",["CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",120],[],""],[],[],["VSM_M81_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_M81",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5]]],["VSM_M81_Backpack_Kitbag",[["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShell",4,1],["CUP_120Rnd_TE4_LRT4_Green_Tracer_762x51_Belt_M",3,120]]],"VSM_Mich2000_2_M81","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
["2BNB Marksman M81",[["SMA_HK417_16in","SMA_supp_762","SMA_SFPEQ_HK417TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_20Rnd_762x51mm_M80A1_EPR_IR",20],[],"bipod_01_F_blk"],[],[],["VSM_M81_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_M81",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5],["SMA_20Rnd_762x51mm_M80A1_EPR_IR",7,20]]],["VSM_M81_Backpack_Kitbag",[["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShell",4,1],["SMA_20Rnd_762x51mm_M80A1_EPR_IR",7,20],["20Rnd_762x51_Mag",7,20]]],"VSM_Mich2000_2_M81","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
["2BNB Rifleman M81",[["SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",["rhs_mag_30Rnd_556x45_M855A1_Stanag",30],[],""],[],[],["VSM_M81_Camo",[["ACE_fieldDressing",4],["ACE_packingBandage",2],["ACE_morphine",2],["ACE_tourniquet",2],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1]]],["VSM_FAPC_Operator_M81",[["ACE_fieldDressing",4],["ACE_elasticBandage",7],["ACE_quikclot",7],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",4],["ACE_IR_Strobe_Item",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_packingBandage",9],["ACE_tourniquet",5],["ACE_morphine",5]]],["VSM_M81_Backpack_Kitbag",[["ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30],["ACE_30Rnd_556x45_Stanag_Mk262_mag",8,30],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["CUP_HandGrenade_M67",2,1],["SmokeShell",4,1]]],"VSM_Mich2000_2_M81","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",["ACE_VectorDay","","","",[],[],""],["ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"]]] call ace_arsenal_fnc_addDefaultLoadout;
//-------------------------------------------------------------------------------
