//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.11.1.1905231
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_Norway2BNB {
        displayName = "Norwegian Forces";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\Norway_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Norway_ca.paa";
        priority = 0;
    };
};