//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 196.146114 on Stable branch
// Generated with ALiVE version 1.11.3.1905291
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_JapanArmy {
        displayName = "Japanese Self Defence Force";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        priority = 0;
    };
};