//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 188.145285 on Stable branch
// Generated with ALiVE version 1.9.1.1901021
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_UKTerrorists_Black {
        displayName = "Terrorists";
        side = 0;
        flag = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_tkm_co";
        icon = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_tkm_co";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_UKTerrorists_Black {
            name = "Terrorists";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

                class o_ukterrorists_specops_blyat_8_black {
                    name = "Blyat 8";
                    side = 0;
                    faction = "O_UKTerrorists_Black";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_UKTerrorists_SL_Black_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Marksman_Black_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_MG_Black_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Medic_Black_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_AT_Black_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Rifleman_Black_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Rifleman_Black_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Rifleman_Black_01";
                    };
                };

                class o_ukterrorists_specops_blyat5_black {
                    name = "Blyat5";
                    side = 0;
                    faction = "O_UKTerrorists_Black";
                    icon = "\A3\ui_f\data\map\markers\nato\o_unknown.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_UKTerrorists_SL_Black_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_AT_Black_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Marksman_Black_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Medic_Black_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Rifleman_Black_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_medic;
    class rhsgref_ins_medic_OCimport_01 : rhsgref_ins_medic { scope = 0; class EventHandlers; };
    class rhsgref_ins_medic_OCimport_02 : rhsgref_ins_medic_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_grenadier_rpg;
    class rhsgref_ins_grenadier_rpg_OCimport_01 : rhsgref_ins_grenadier_rpg { scope = 0; class EventHandlers; };
    class rhsgref_ins_grenadier_rpg_OCimport_02 : rhsgref_ins_grenadier_rpg_OCimport_01 { class EventHandlers; };


    class O_UKTerrorists_Rifleman_Black_01 : O_Soldier_F_OCimport_02 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};

        weapons[] = {"SMA_ACRREMblk_N","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"SMA_ACRREMblk_N","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};

        backpack = "B_ViperLightHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"SMA_ACRREMblk_N","SMA_supp1b_556","rhsusf_acc_anpeq15A","sma_spitfire_03_rds_black",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{"rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",{"rhsusf_mag_17Rnd_9x19_JHP",17},{},""},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",9,30}}},{"B_ViperLightHarness_blk_F",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_salineIV_500",2},{"ACE_Banana",3},{"ACE_packingBandage",10},{"rhs_mag_mk84",5,1},{"ACE_Chemlight_HiGreen",6,1},{"CUP_HandGrenade_L109A1_HE",3,1},{"CUP_HandGrenade_L109A2_HE",3,1},{"SmokeShell",8,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'ENFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "ENFlagW";

    };

    class O_UKTerrorists_Medic_Black_01 : rhsgref_ins_medic_OCimport_02 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};

        weapons[] = {"SMA_ACRREMblk_N","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"SMA_ACRREMblk_N","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};

        backpack = "CUP_B_USPack_Black";

        ALiVE_orbatCreator_loadout[] = {{"SMA_ACRREMblk_N","SMA_supp1b_556","rhsusf_acc_anpeq15A","sma_spitfire_03_rds_black",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{"rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",{"rhsusf_mag_17Rnd_9x19_JHP",17},{},""},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",9,30}}},{"CUP_B_USPack_Black",{{"ACE_quikclot",21},{"ACE_elasticBandage",21},{"ACE_fieldDressing",25},{"ACE_epinephrine",17},{"ACE_morphine",16},{"ACE_salineIV_500",4},{"ACE_Banana",3},{"ACE_surgicalKit",1},{"ACE_packingBandage",13},{"ACE_salineIV_250",7},{"ACE_salineIV",4},{"ACE_Chemlight_HiGreen",6,1},{"SmokeShell",8,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1}}},"rhsusf_opscore_bk","",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'ENFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "ENFlagW";

    };

    class O_UKTerrorists_AT_Black_01 : rhsgref_ins_grenadier_rpg_OCimport_02 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "AT";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};

        weapons[] = {"SMA_ACRREMblk_N","launch_RPG32_F","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"SMA_ACRREMblk_N","launch_RPG32_F","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","RPG32_F","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","RPG32_F","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};

        backpack = "B_ViperHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"SMA_ACRREMblk_N","SMA_supp1b_556","rhsusf_acc_anpeq15A","sma_spitfire_03_rds_black",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{"launch_RPG32_F","","","",{"RPG32_F",1},{},""},{"rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",{"rhsusf_mag_17Rnd_9x19_JHP",17},{},""},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",9,30}}},{"B_ViperHarness_blk_F",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",10},{"ACE_Chemlight_HiGreen",6,1},{"SmokeShell",4,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1},{"RPG32_F",3,1}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Peltor_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'ENFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "ENFlagW";

    };

    class O_UKTerrorists_SL_Black_01 : O_UKTerrorists_Rifleman_Black_01 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "SL";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};

        weapons[] = {"SMA_ACRREMblk_N","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"SMA_ACRREMblk_N","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};

        backpack = "TFAR_rt1523g_black";

        ALiVE_orbatCreator_loadout[] = {{"SMA_ACRREMblk_N","SMA_supp1b_556","rhsusf_acc_anpeq15A","sma_spitfire_03_rds_black",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{"rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",{"rhsusf_mag_17Rnd_9x19_JHP",17},{},""},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",9,30}}},{"TFAR_rt1523g_black",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_salineIV_500",2},{"ACE_Banana",3},{"ACE_packingBandage",1},{"ACE_Chemlight_HiGreen",5,1},{"SmokeShellYellow",2,1},{"SmokeShellRed",2,1},{"SmokeShellPurple",2,1},{"SmokeShellOrange",2,1},{"SmokeShellGreen",1,1},{"ACE_HandFlare_White",1,1}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Peltor_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'ENFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "ENFlagW";

    };

    class O_UKTerrorists_Marksman_Black_01 : O_UKTerrorists_Rifleman_Black_01 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};

        weapons[] = {"SMA_SKS_F","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"SMA_SKS_F","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};

        magazines[] = {"SMA_30Rnd_762x39_7n23_AP_Red","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","SMA_30Rnd_762x39_7n23_AP_Red","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};
        respawnMagazines[] = {"SMA_30Rnd_762x39_7n23_AP_Red","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","SMA_30Rnd_762x39_7n23_AP_Red","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};

        backpack = "B_ViperLightHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"SMA_SKS_F","SMA_supp_762","rhsusf_acc_anpeq15A","sma_spitfire_03_rds_black",{"SMA_30Rnd_762x39_7n23_AP_Red",30},{},""},{},{"rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",{"rhsusf_mag_17Rnd_9x19_JHP",17},{},""},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"SMA_30Rnd_762x39_SKS_7n23_AP",4,30},{"SMA_30Rnd_762x39_SKS_FMJ",5,30}}},{"B_ViperLightHarness_blk_F",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_salineIV_500",2},{"ACE_Banana",3},{"ACE_packingBandage",10},{"rhs_mag_mk84",5,1},{"ACE_Chemlight_HiGreen",6,1},{"CUP_HandGrenade_L109A1_HE",3,1},{"CUP_HandGrenade_L109A2_HE",3,1},{"SmokeShell",8,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1},{"SMA_30Rnd_762x39_7n23_AP_Red",1,30}}},"rhsusf_opscore_bk","",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'ENFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "ENFlagW";

    };

    class O_UKTerrorists_MG_Black_01 : O_UKTerrorists_Rifleman_Black_01 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "MG";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"};

        weapons[] = {"sma_minimi_mk3_762tlb","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"sma_minimi_mk3_762tlb","rhsusf_weap_glock17g4","Laserdesignator_01_khk_F"};

        magazines[] = {"SMA_150Rnd_762_M80A1","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","SMA_150Rnd_762_M80A1","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};
        respawnMagazines[] = {"SMA_150Rnd_762_M80A1","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries","SMA_150Rnd_762_M80A1","rhsusf_mag_17Rnd_9x19_JHP","Laserbatteries"};

        backpack = "B_ViperHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"sma_minimi_mk3_762tlb","sma_gemtech_one_blk","acc_flashlight","sma_spitfire_03_rds_black",{"SMA_150Rnd_762_M80A1",150},{},""},{},{"rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",{"rhsusf_mag_17Rnd_9x19_JHP",17},{},""},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",4,17},{"SMA_150Rnd_762_M80A1",2,150}}},{"B_ViperHarness_blk_F",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_salineIV_500",2},{"ACE_Banana",3},{"ACE_packingBandage",10},{"rhs_mag_mk84",5,1},{"ACE_Chemlight_HiGreen",6,1},{"CUP_HandGrenade_L109A1_HE",3,1},{"CUP_HandGrenade_L109A2_HE",3,1},{"SmokeShell",8,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1},{"SMA_150Rnd_762_M80A1",1,150}}},"rhsusf_opscore_bk","VSM_balaclava_Black",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","A3_GPNVG18b_BLK_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'ENFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "ENFlagW";

    };

};
