//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 188.145285 on Stable branch
// Generated with ALiVE version 1.9.1.1901021
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_UKTerrorists_Black {
        displayName = "Terrorists";
        side = 0;
        flag = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_tkm_co";
        icon = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_tkm_co";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_UKTerrorists_Black {
            name = "Terrorists";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

                class o_ukterrorists_specops_blyat_8_black {
                    name = "Blyat 8";
                    side = 0;
                    faction = "O_UKTerrorists_Black";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_UKTerrorists_SL_Black_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Marksman_Black_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_MG_Black_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Medic_Black_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_AT_Black_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Rifleman_Black_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Rifleman_Black_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Rifleman_Black_01";
                    };
                };

                class o_ukterrorists_specops_blyat_5_black {
                    name = "Blyat5";
                    side = 0;
                    faction = "O_UKTerrorists_Black";
                    icon = "\A3\ui_f\data\map\markers\nato\o_unknown.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_UKTerrorists_SL_Black_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_AT_Black_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Marksman_Black_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Medic_Black_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_UKTerrorists_Rifleman_Black_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_medic;
    class rhsgref_ins_medic_OCimport_01 : rhsgref_ins_medic { scope = 0; class EventHandlers; };
    class rhsgref_ins_medic_OCimport_02 : rhsgref_ins_medic_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_grenadier_rpg;
    class rhsgref_ins_grenadier_rpg_OCimport_01 : rhsgref_ins_grenadier_rpg { scope = 0; class EventHandlers; };
    class rhsgref_ins_grenadier_rpg_OCimport_02 : rhsgref_ins_grenadier_rpg_OCimport_01 { class EventHandlers; };


    class O_UKTerrorists_Rifleman_Black_01 : O_Soldier_F_OCimport_02 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_TK","LanguageENGB_F","VSM_FaceMask_black","G_IRAN_default"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};

        weapons[] = {"rhs_weap_hk416d10","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"rhs_weap_hk416d10","Laserdesignator_01_khk_F"};

        magazines[] = {"ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries","ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries"};
        respawnMagazines[] = {"ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries","ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries"};

        backpack = "B_ViperLightHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_hk416d10","","","optic_Hamr",{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",30},{},""},{},{},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2},{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",1,30}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"ACE_bloodIV_500",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",8,30}}},{"B_ViperLightHarness_blk_F",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_salineIV_500",2},{"ACE_Banana",3},{"ACE_packingBandage",10},{"ACE_adenosine",2},{"rhs_mag_mk84",5,1},{"ACE_Chemlight_HiGreen",6,1},{"SmokeShell",8,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'SCTFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "SCTFlagW";

    };

    class O_UKTerrorists_Medic_Black_01 : rhsgref_ins_medic_OCimport_02 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_Euro","LanguageENGB_F","VSM_FaceMask_black","G_CIVIL_male"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};

        weapons[] = {"rhs_weap_mk18_KAC","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"rhs_weap_mk18_KAC","Laserdesignator_01_khk_F"};

        magazines[] = {"ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries","ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries"};
        respawnMagazines[] = {"ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries","ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries"};

        backpack = "B_ViperHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_mk18_KAC","","","optic_Hamr",{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",30},{},""},{},{},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2},{"ACE_bloodIV_500",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"ACE_adenosine",5},{"ACE_salineIV_500",2},{"ACE_morphine",2},{"ACE_elasticBandage",6},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",8,30}}},{"B_ViperHarness_blk_F",{{"ACE_elasticBandage",30},{"ACE_packingBandage",10},{"ACE_quikclot",5},{"ACE_bloodIV",18},{"ACE_bloodIV_500",5},{"ACE_morphine",10},{"ACE_epinephrine",10},{"ACE_adenosine",10},{"ACE_bloodIV_250",5}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Peltor_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_UKTerrorists_AT_Black_01 : rhsgref_ins_grenadier_rpg_OCimport_02 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
		vehicleclass = "ASTR_Infanrty";
        displayName = "AT";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_Euro","LanguageENGB_F","VSM_FaceMask_black","G_CIVIL_male"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};

        weapons[] = {"rhs_weap_m4","launch_RPG32_green_F","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"rhs_weap_m4","launch_RPG32_green_F","Laserdesignator_01_khk_F"};

        magazines[] = {"ACE_30Rnd_556x45_Stanag_M995_AP_mag","RPG32_F","Laserbatteries","ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries"};
        respawnMagazines[] = {"ACE_30Rnd_556x45_Stanag_M995_AP_mag","RPG32_F","Laserbatteries","ACE_30Rnd_556x45_Stanag_M995_AP_mag","Laserbatteries"};

        backpack = "B_ViperHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4","","","RKSL_optic_EOT552",{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",30},{},""},{"launch_RPG32_green_F","","","",{"RPG32_F",1},{},""},{},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2},{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",1,30}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",7,30}}},{"B_ViperHarness_blk_F",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",10},{"ACE_Chemlight_HiGreen",6,1},{"SmokeShell",4,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1},{"RPG32_F",3,1}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Peltor_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'SCTFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "SCTFlagW";

    };

    class O_UKTerrorists_SL_Black_01 : O_UKTerrorists_Rifleman_Black_01 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "SL";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_TK","LanguageENGB_F","VSM_FaceMask_black","G_CIVIL_male"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};

        weapons[] = {"UK3CB_BAF_L85A2_UGL","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"UK3CB_BAF_L85A2_UGL","Laserdesignator_01_khk_F"};

        magazines[] = {"ACE_30Rnd_556x45_Stanag_M995_AP_mag","UK3CB_BAF_1Rnd_HE_Grenade_Shell","Laserbatteries","ACE_30Rnd_556x45_Stanag_M995_AP_mag","UK3CB_BAF_1Rnd_HE_Grenade_Shell","Laserbatteries"};
        respawnMagazines[] = {"ACE_30Rnd_556x45_Stanag_M995_AP_mag","UK3CB_BAF_1Rnd_HE_Grenade_Shell","Laserbatteries","ACE_30Rnd_556x45_Stanag_M995_AP_mag","UK3CB_BAF_1Rnd_HE_Grenade_Shell","Laserbatteries"};

        backpack = "TFAR_rt1523g_black";

        ALiVE_orbatCreator_loadout[] = {{"UK3CB_BAF_L85A2_UGL","","","optic_Hamr",{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",30},{"UK3CB_BAF_1Rnd_HE_Grenade_Shell",1},""},{},{},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2},{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",1,30}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"UK3CB_BAF_1Rnd_HE_Grenade_Shell",3,1},{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",8,30}}},{"TFAR_rt1523g_black",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_salineIV_500",2},{"ACE_Banana",3},{"ACE_packingBandage",1},{"ACE_Chemlight_HiGreen",5,1},{"SmokeShellYellow",2,1},{"SmokeShellRed",2,1},{"SmokeShellPurple",2,1},{"SmokeShellOrange",2,1},{"SmokeShellGreen",1,1},{"ACE_HandFlare_White",1,1}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Peltor_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'SCTFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "SCTFlagW";

    };

    class O_UKTerrorists_Marksman_Black_01 : O_UKTerrorists_Rifleman_Black_01 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_TK","LanguageENGB_F","VSM_FaceMask_black","G_CIVIL_male"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","NVGoggles_mas_nor_hv"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","NVGoggles_mas_nor_hv"};

        weapons[] = {"UK3CB_BAF_L129A1","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"UK3CB_BAF_L129A1","Laserdesignator_01_khk_F"};

        magazines[] = {"UK3CB_BAF_762_L42A1_20Rnd","Laserbatteries","UK3CB_BAF_762_L42A1_20Rnd","Laserbatteries"};
        respawnMagazines[] = {"UK3CB_BAF_762_L42A1_20Rnd","Laserbatteries","UK3CB_BAF_762_L42A1_20Rnd","Laserbatteries"};

        backpack = "B_ViperLightHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"UK3CB_BAF_L129A1","","","optic_DMS",{"UK3CB_BAF_762_L42A1_20Rnd",20},{},""},{},{},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",5,17},{"UK3CB_BAF_762_L42A1_20Rnd",7,20}}},{"B_ViperLightHarness_blk_F",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_salineIV_500",2},{"ACE_Banana",3},{"ACE_packingBandage",10},{"rhs_mag_mk84",5,1},{"ACE_Chemlight_HiGreen",6,1},{"SmokeShell",8,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Peltor_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr","NVGoggles_mas_nor_hv"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'SCTFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "SCTFlagW";

    };

    class O_UKTerrorists_MG_Black_01 : O_UKTerrorists_Rifleman_Black_01 {
        author = "Maj. D. Ford";
        scope = 2;
        scopeCurator = 2;
        displayName = "MG";
        side = 0;
        faction = "O_UKTerrorists_Black";

        identityTypes[] = {"Head_TK","LanguageENGB_F","VSM_FaceMask_black","G_IRAN_default"};

        uniformClass = "rhs_uniform_g3_blk";

        linkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};
        respawnlinkedItems[] = {"V_PlateCarrier2_blk","rhsusf_opscore_bk","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr"};

        weapons[] = {"UK3CB_BAF_L110_762","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"UK3CB_BAF_L110_762","Laserdesignator_01_khk_F"};

        magazines[] = {"UK3CB_BAF_762_100Rnd","Laserbatteries","UK3CB_BAF_762_100Rnd","Laserbatteries"};
        respawnMagazines[] = {"UK3CB_BAF_762_100Rnd","Laserbatteries","UK3CB_BAF_762_100Rnd","Laserbatteries"};

        backpack = "B_ViperHarness_blk_F";

        ALiVE_orbatCreator_loadout[] = {{"UK3CB_BAF_L110_762","","","optic_Hamr",{"UK3CB_BAF_762_100Rnd",100},{},""},{},{},{"rhs_uniform_g3_blk",{{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",12},{"ACE_Flashlight_XL50",1},{"ACE_IR_Strobe_Item",2}}},{"V_PlateCarrier2_blk",{{"ACE_bodyBag",2},{"rhsusf_mag_17Rnd_9x19_FMJ",4,17},{"rhsusf_100Rnd_762x51_m61_ap",3,100}}},{"B_ViperHarness_blk_F",{{"ACE_quikclot",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_salineIV_500",2},{"ACE_Banana",3},{"ACE_packingBandage",10},{"rhs_mag_mk84",5,1},{"ACE_Chemlight_HiGreen",6,1},{"SmokeShell",8,1},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"SmokeShellRed",2,1},{"rhsusf_100Rnd_762x51_m61_ap",4,100}}},"rhsusf_opscore_bk","VSM_Balaclava2_black_Peltor_Goggles",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","TFAR_microdagr",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'SCTFlagW'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "SCTFlagW";

    };

};