//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.11.3.1905291
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_Chernarus_Winter {
        displayName = "Chernarus Winter Force";
        side = 2;
        flag = "\UK3CB_Factions\addons\UK3CB_Factions_CCM\Flag\ccm_i_marker_co.paa";
        icon = "\UK3CB_Factions\addons\UK3CB_Factions_CCM\Flag\ccm_i_marker_co.paa";
        priority = 0;
    };
};