//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.11.3.1905291
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class Indep {

        class I_Chernarus_Winter {
            name = "Chernarus Winter Force";

            class Infantry {
                name = "Infantry";

                class i_chernarus_infantry_squad_winter {
                    name = "Squad";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_TLeader_Winter";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Grenadire_Winter";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Medic_Winter";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Machinegunner";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_AT_Winter";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_Winter";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Sniper_Winter";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_Winter";
                    };
                };

                class i_chernarus_infantry_sentry_winter {
                    name = "Sentry";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_Grenadire_Winter";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_Winter";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class i_chernarus_motorized_squad_winter {
                    name = "Squad";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_PragaV3S_TClosed_Winter";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_TLeader_Winter";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Grenadire_Winter";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Machinegunner";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Medic_Winter";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_AT_Winter";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_Winter";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_Winter";
                    };
                };

                class i_chernarus_motorized_sentry_winter {
                    name = "Sentry";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_UAZ_DShKM_Winter";
                    };
                    class Unit1 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_AT_Winter";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class i_chernarus_mechanized_sentry_winter {
                    name = "Sentry";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_BTR_60_Winter";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_AT_Winter";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Rifleman_Winter";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class i_chernarus_armored_sentry_winter {
                    name = "Sentry";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_T72_Winter";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class i_chernarus_artillery_sentry_winter {
                    name = "Sentry";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_Ural_BM21_Winter";
                    };
                };

            };

            class Air {
                name = "Air";

                class i_chernarus_air_helicopter_sentry_winter {
                    name = "Helicopter Sentry";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_Mi_24_Winter";
                    };
                    class Unit1 {
                        position[] = {21,-30,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Mi_24_Winter";
                    };
                };

                class i_chernarus_air_plane_sentry_winter {
                    name = "Plane Sentry";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_L39_AA_Winter";
                    };
                    class Unit1 {
                        position[] = {15,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_L39_AA_Winter";
                    };
                };

                class i_chernarus_air_bomber_sentry_winter {
                    name = "Bomber Sentry";
                    side = 2;
                    faction = "I_Chernarus_Winter";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_Chernarus_Su25_Cluster_Winter";
                    };
                    class Unit1 {
                        position[] = {22,-23,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_Chernarus_Su25_Cluster_Winter";
                    };
                };

            };


        };

    };
};
