//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.11.3.1905291
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LOP_UKR_Infantry_officer;
    class LOP_UKR_Infantry_officer_OCimport_01 : LOP_UKR_Infantry_officer { scope = 0; class EventHandlers; };
    class LOP_UKR_Infantry_officer_OCimport_02 : LOP_UKR_Infantry_officer_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_uaz_dshkm;
    class rhsgref_ins_uaz_dshkm_OCimport_01 : rhsgref_ins_uaz_dshkm { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_ins_uaz_dshkm_OCimport_02 : rhsgref_ins_uaz_dshkm_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class rhsgref_ins_g_bmp1;
    class rhsgref_ins_g_bmp1_OCimport_01 : rhsgref_ins_g_bmp1 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_ins_g_bmp1_OCimport_02 : rhsgref_ins_g_bmp1_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class MainTurret;
            class Com_BMP1;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class CargoTurret_10;
        };
    };

    class rhsgref_ins_g_btr60;
    class rhsgref_ins_g_btr60_OCimport_01 : rhsgref_ins_g_btr60 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_ins_g_btr60_OCimport_02 : rhsgref_ins_g_btr60_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class rhsgref_ins_g_ural_Zu23;
    class rhsgref_ins_g_ural_Zu23_OCimport_01 : rhsgref_ins_g_ural_Zu23 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_ins_g_ural_Zu23_OCimport_02 : rhsgref_ins_g_ural_Zu23_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class rhsgref_ins_g_BM21;
    class rhsgref_ins_g_BM21_OCimport_01 : rhsgref_ins_g_BM21 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_ins_g_BM21_OCimport_02 : rhsgref_ins_g_BM21_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LOP_UKR_Mi24V_AT;
    class LOP_UKR_Mi24V_AT_OCimport_01 : LOP_UKR_Mi24V_AT { scope = 0; class EventHandlers; class Turrets; };
    class LOP_UKR_Mi24V_AT_OCimport_02 : LOP_UKR_Mi24V_AT_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class RHS_Mi8mt_vv;
    class RHS_Mi8mt_vv_OCimport_01 : RHS_Mi8mt_vv { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Mi8mt_vv_OCimport_02 : RHS_Mi8mt_vv_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class BackTurret;
        };
    };

    class RHS_Mi8AMTSh_vvsc;
    class RHS_Mi8AMTSh_vvsc_OCimport_01 : RHS_Mi8AMTSh_vvsc { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Mi8AMTSh_vvsc_OCimport_02 : RHS_Mi8AMTSh_vvsc_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class CopilotTurret;
            class SideTurret;
            class BackTurret;
            class FrontTurret;
        };
    };

    class RHS_Su25SM_vvs;
    class RHS_Su25SM_vvs_OCimport_01 : RHS_Su25SM_vvs { scope = 0; class EventHandlers; };
    class RHS_Su25SM_vvs_OCimport_02 : RHS_Su25SM_vvs_OCimport_01 { scope = 0; class EventHandlers; };

    class I_Plane_Fighter_03_dynamicLoadout_F;
    class I_Plane_Fighter_03_dynamicLoadout_F_OCimport_01 : I_Plane_Fighter_03_dynamicLoadout_F { scope = 0; class EventHandlers; };
    class I_Plane_Fighter_03_dynamicLoadout_F_OCimport_02 : I_Plane_Fighter_03_dynamicLoadout_F_OCimport_01 { scope = 0; class EventHandlers; };

    class LOP_AFR_T55;
    class LOP_AFR_T55_OCimport_01 : LOP_AFR_T55 { scope = 0; class EventHandlers; class Turrets; };
    class LOP_AFR_T55_OCimport_02 : LOP_AFR_T55_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhsgref_ins_g_t72bc;
    class rhsgref_ins_g_t72bc_OCimport_01 : rhsgref_ins_g_t72bc { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_ins_g_t72bc_OCimport_02 : rhsgref_ins_g_t72bc_OCimport_01 {
        class EventHandlers;
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class rhsgref_ins_uaz;
    class rhsgref_ins_uaz_OCimport_01 : rhsgref_ins_uaz { scope = 0; class EventHandlers; };
    class rhsgref_ins_uaz_OCimport_02 : rhsgref_ins_uaz_OCimport_01 { scope = 0; class EventHandlers; };


    class I_Chernarus_Man_Winter : LOP_UKR_Infantry_officer_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Man_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Man";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"Binocular"};
        respawnWeapons[] = {"Binocular"};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"rhs_mag_rdg2_white",1,1}}},{"V_mas_nor_PlateCarrierLR_wint",{}},{"UK3CB_BAF_B_Kitbag_Arctic",{}},"H_mas_nor_beanie_w","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Rifleman_Winter : I_Chernarus_Man_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Rifleman_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak103_2","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak103_2","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_30Rnd_762x39mm_polymer"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_30Rnd_762x39mm_polymer"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak103_2","rhs_acc_dtk","","rhs_acc_ekp8_02",{"rhs_30Rnd_762x39mm_polymer",30},{},""},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"rhs_mag_rdg2_white",1,1},{"30Rnd_762x39_Mag_Tracer_Green_F",2,30}}},{"V_mas_nor_PlateCarrierLR_wint",{{"ACE_fieldDressing",6},{"ACE_quikclot",6},{"ACE_EarPlugs",1},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",4},{"ACE_tourniquet",4},{"rhs_mag_an_m8hc",3,1},{"rhs_mag_rgn",4,1},{"30Rnd_762x39_Mag_Tracer_Green_F",10,30}}},{"UK3CB_BAF_B_Kitbag_Arctic",{{"30Rnd_762x39_Mag_Tracer_Green_F",6,30}}},"H_mas_nor_beanie_w","G_Balaclava_blk",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Rifleman_AT_Winter : I_Chernarus_Rifleman_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Rifleman_AT_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman AT";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak103_2","rhs_weap_rpg7","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak103_2","rhs_weap_rpg7","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_rpg7_PG7V_mag","rhs_30Rnd_762x39mm_polymer"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_rpg7_PG7V_mag","rhs_30Rnd_762x39mm_polymer"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak103_2","rhs_acc_dtk","","rhs_acc_ekp8_02",{"rhs_30Rnd_762x39mm_polymer",30},{},""},{"rhs_weap_rpg7","","","rhs_acc_pgo7v3",{"rhs_rpg7_PG7V_mag",1},{},""},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"rhs_mag_rdg2_white",1,1},{"30Rnd_762x39_Mag_Tracer_Green_F",2,30}}},{"V_mas_nor_PlateCarrierLR_wint",{{"ACE_fieldDressing",6},{"ACE_quikclot",6},{"ACE_EarPlugs",1},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",4},{"ACE_tourniquet",4},{"rhs_mag_an_m8hc",3,1},{"rhs_mag_rgn",4,1},{"30Rnd_762x39_Mag_Tracer_Green_F",10,30}}},{"UK3CB_BAF_B_Kitbag_Arctic",{{"30Rnd_762x39_Mag_Tracer_Green_F",6,30},{"rhs_rpg7_PG7V_mag",3,1},{"rhs_rpg7_PG7VR_mag",1,1},{"rhs_rpg7_PG7VL_mag",1,1}}},"H_mas_nor_beanie_w","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Crew_Winter : I_Chernarus_Man_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Crew_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crew";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","UK3CB_BAF_H_Mk7_Win_A","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","UK3CB_BAF_H_Mk7_Win_A","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74un","Binocular"};
        respawnWeapons[] = {"rhs_weap_aks74un","Binocular"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74un","rhs_acc_pgs64_74un","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",4},{"ACE_packingBandage",4},{"ACE_tourniquet",3},{"ACE_quikclot",2},{"ACE_EarPlugs",1},{"ACE_epinephrine",1},{"ACE_morphine",2},{"rhs_mag_rdg2_white",1,1}}},{"V_mas_nor_PlateCarrierLR_wint",{{"rhs_30Rnd_545x39_AK_plum_green",8,30},{"rhs_mag_rdg2_white",3,1},{"rhs_mag_nspn_yellow",2,1}}},{"UK3CB_BAF_B_Kitbag_Arctic",{}},"UK3CB_BAF_H_Mk7_Win_A","rhsusf_shemagh_gogg_white",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Pilot_Winter : I_Chernarus_Crew_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Pilot_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","rhsusf_hgu56p_visor_white","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","rhsusf_hgu56p_visor_white","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74un","Binocular"};
        respawnWeapons[] = {"rhs_weap_aks74un","Binocular"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74un","rhs_acc_pgs64_74un","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",4},{"ACE_packingBandage",4},{"ACE_tourniquet",3},{"ACE_quikclot",2},{"ACE_EarPlugs",1},{"ACE_epinephrine",1},{"ACE_morphine",2},{"rhs_mag_rdg2_white",1,1}}},{"V_mas_nor_PlateCarrierLR_wint",{{"rhs_30Rnd_545x39_AK_plum_green",8,30},{"rhs_mag_rdg2_white",3,1},{"rhs_mag_nspn_yellow",2,1}}},{"UK3CB_BAF_B_Kitbag_Arctic",{}},"rhsusf_hgu56p_visor_white","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Sniper_Winter : I_Chernarus_Man_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Sniper_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_svds","Binocular"};
        respawnWeapons[] = {"rhs_weap_svds","Binocular"};

        magazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_10Rnd_762x54mmR_7N1"};
        respawnMagazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_10Rnd_762x54mmR_7N1"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_svds","","","rhs_acc_pso1m21",{"rhs_10Rnd_762x54mmR_7N1",10},{},""},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",5},{"ACE_packingBandage",4},{"ACE_morphine",2},{"ACE_tourniquet",3},{"ACE_quikclot",2},{"ACE_EarPlugs",1},{"ACE_epinephrine",1},{"rhs_mag_rdg2_white",1,1}}},{"V_mas_nor_PlateCarrierLR_wint",{{"ACE_10Rnd_762x54_Tracer_mag",14,10},{"rhs_mag_rdg2_white",3,1},{"rhs_mag_rgn",1,1}}},{"UK3CB_BAF_B_Kitbag_Arctic",{}},"H_mas_nor_beanie_w","G_Bandanna_blk",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Medic_Winter : I_Chernarus_Rifleman_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Medic_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak103_2","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak103_2","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_30Rnd_762x39mm_polymer"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_30Rnd_762x39mm_polymer"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak103_2","rhs_acc_dtk","","rhs_acc_ekp8_02",{"rhs_30Rnd_762x39mm_polymer",30},{},""},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"rhs_mag_rdg2_white",1,1},{"30Rnd_762x39_Mag_Tracer_Green_F",2,30}}},{"V_mas_nor_PlateCarrierLR_wint",{{"ACE_fieldDressing",6},{"ACE_quikclot",6},{"ACE_EarPlugs",1},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",4},{"ACE_tourniquet",4},{"rhs_mag_an_m8hc",3,1},{"rhs_mag_rgn",4,1},{"30Rnd_762x39_Mag_Tracer_Green_F",10,30}}},{"UK3CB_BAF_B_Kitbag_Arctic",{{"ACE_surgicalKit",4},{"ACE_packingBandage",12},{"ACE_morphine",6},{"ACE_epinephrine",6},{"ACE_EarPlugs",1},{"ACE_quikclot",6},{"ACE_fieldDressing",8},{"ACE_atropine",3},{"ACE_adenosine",3},{"ACE_tourniquet",6},{"30Rnd_762x39_Mag_Tracer_Green_F",6,30}}},"H_mas_nor_beanie_w","G_Bandanna_shades",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Machinegunner : I_Chernarus_Rifleman_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Machinegunner.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machinegunner";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_pkm","Binocular"};
        respawnWeapons[] = {"rhs_weap_pkm","Binocular"};

        magazines[] = {"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};
        respawnMagazines[] = {"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pkm","","","",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",3},{"ACE_packingBandage",2},{"ACE_morphine",1},{"ACE_tourniquet",1},{"ACE_EarPlugs",1},{"ACE_epinephrine",1},{"rhs_mag_rdg2_white",1,1},{"30Rnd_762x39_Mag_Tracer_Green_F",2,30}}},{"V_mas_nor_PlateCarrierLR_wint",{{"ACE_fieldDressing",3},{"ACE_quikclot",2},{"ACE_epinephrine",3},{"ACE_morphine",1},{"ACE_tourniquet",4},{"ACE_packingBandage",1},{"rhs_mag_an_m8hc",2,1},{"rhs_mag_rgn",1,1},{"30Rnd_762x39_Mag_Tracer_Green_F",10,30},{"rhs_100Rnd_762x54mmR_green",1,100}}},{"UK3CB_BAF_B_Kitbag_Arctic",{{"30Rnd_762x39_Mag_Tracer_Green_F",6,30},{"rhs_100Rnd_762x54mmR_green",3,100}}},"H_mas_nor_beanie_w","G_Bandanna_blk",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Officer_Winter : I_Chernarus_Man_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Officer_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","rhsusf_patrolcap_ucp","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","rhsusf_patrolcap_ucp","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_pya","Binocular"};
        respawnWeapons[] = {"rhs_weap_pya","Binocular"};

        magazines[] = {"rhs_mag_9x19_17","rhs_mag_9x19_17"};
        respawnMagazines[] = {"rhs_mag_9x19_17","rhs_mag_9x19_17"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"rhs_weap_pya","","","",{"rhs_mag_9x19_17",17},{},""},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",3},{"ACE_packingBandage",5},{"ACE_morphine",2},{"ACE_tourniquet",3},{"ACE_quikclot",2},{"ACE_EarPlugs",1},{"ACE_epinephrine",1},{"rhs_mag_rdg2_white",1,1}}},{"V_mas_nor_PlateCarrierLR_wint",{{"16Rnd_9x21_green_Mag",10,17}}},{},"rhsusf_patrolcap_ucp","rhsusf_shemagh_gogg_white",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_TLeader_Winter : I_Chernarus_Rifleman_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_TLeader_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak103_2","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak103_2","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_30Rnd_762x39mm_polymer"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_30Rnd_762x39mm_polymer"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak103_2","rhs_acc_dtk","","rhs_acc_pgo7v2",{"rhs_30Rnd_762x39mm_polymer",30},{},""},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"rhs_mag_rdg2_white",1,1},{"30Rnd_762x39_Mag_Tracer_Green_F",2,30}}},{"V_mas_nor_PlateCarrierLR_wint",{{"ACE_fieldDressing",6},{"ACE_quikclot",6},{"ACE_EarPlugs",1},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",4},{"ACE_tourniquet",4},{"rhs_mag_an_m8hc",3,1},{"rhs_mag_rgn",4,1},{"30Rnd_762x39_Mag_Tracer_Green_F",10,30}}},{"UK3CB_BAF_B_Kitbag_Arctic",{{"30Rnd_762x39_Mag_Tracer_Green_F",6,30}}},"H_mas_nor_beanie_w","G_Bandanna_shades",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Grenadier_Winter : I_Chernarus_TLeader_Winter {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Grenadier_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 2;
        faction = "I_Chernarus_Winter";

        identityTypes[] = {"Head_Euro","LanguageRUS","Head_Russian"};

        uniformClass = "LOP_U_ISTS_Fatigue_07";

        linkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_mas_nor_PlateCarrierLR_wint","H_mas_nor_beanie_w","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74mr_gp25","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak74mr_gp25","Binocular"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_30Rnd_545x39_7N10_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_30Rnd_545x39_7N10_AK"};

        backpack = "UK3CB_BAF_B_Kitbag_Arctic";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74mr_gp25","rhs_acc_dtk","","rhs_acc_1p87",{"rhs_30Rnd_545x39_7N10_AK",30},{},""},{},{},{"LOP_U_ISTS_Fatigue_07",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1},{"rhs_mag_rdg2_white",1,1},{"30Rnd_762x39_Mag_Tracer_Green_F",2,30}}},{"V_mas_nor_PlateCarrierLR_wint",{{"ACE_fieldDressing",6},{"ACE_quikclot",6},{"ACE_EarPlugs",1},{"ACE_epinephrine",3},{"ACE_morphine",3},{"ACE_packingBandage",4},{"ACE_tourniquet",4},{"rhs_mag_an_m8hc",3,1},{"rhs_mag_rgn",4,1},{"30Rnd_762x39_Mag_Tracer_Green_F",10,30},{"rhs_30Rnd_545x39_AK_plum_green",3,30}}},{"UK3CB_BAF_B_Kitbag_Arctic",{{"30Rnd_762x39_Mag_Tracer_Green_F",6,30},{"rhs_30Rnd_545x39_AK_plum_green",4,30},{"rhs_VOG25",8,1},{"rhs_VG40TB",3,1},{"rhs_GRD40_White",5,1}}},"H_mas_nor_beanie_w","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_UAZ_DShKM_Winter : rhsgref_ins_uaz_dshkm_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_UAZ_DShKM_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ DShKM";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Crew_Winter";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Rifleman_Winter"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "White";

    };

    class I_Chernarus_BMP_1_Winter : rhsgref_ins_g_bmp1_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_BMP_1_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "BMP-1";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Crew_Winter";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Crew_Winter"; };
            class Com_BMP1 : Com_BMP1 { gunnerType = "I_Chernarus_Crew_Winter"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "ANA";

    };

    class I_Chernarus_BTR_60_Winter : rhsgref_ins_g_btr60_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_BTR_60_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR-60";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Crew_Winter";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Crew_Winter"; };
            class CommanderOptics : CommanderOptics { gunnerType = "I_Chernarus_Crew_Winter"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo1";

    };

    class I_Chernarus_Ural_ZU23 : rhsgref_ins_g_ural_Zu23_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Ural_ZU23.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural ZU-23";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Crew_Winter";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Crew_Winter"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "I_Chernarus_Crew_Winter"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Russia";

    };

    class I_Chernarus_Ural_BM21_Winter : rhsgref_ins_g_BM21_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Ural_BM21_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural BM-21";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Crew_Winter";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Crew_Winter"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Russia";

    };

    class I_Chernarus_Mi_24_Winter : LOP_UKR_Mi24V_AT_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Mi_24_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mi-24";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Pilot_Winter";
        // hiddenSelections[] = {"camo1","camo2","exhaust","tail_decals","n1","n2","moving_map"};
        hiddenSelections[] = {"Camo3"};

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_Chernarus_Mi8_Transport_Winter : RHS_Mi8mt_vv_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Mi8_Transport_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mi-8 Transport";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Pilot_Winter";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
            class BackTurret : BackTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "GREY";

    };

    class I_Chernarus_Mi8_Rockets_Winter : RHS_Mi8AMTSh_vvsc_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Mi8_Rockets_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mi-8 Rockets";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Pilot_Winter";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
            class SideTurret : SideTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
            class BackTurret : BackTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
            class FrontTurret : FrontTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "GREY";

    };

    class I_Chernarus_Su25_Cluster_Winter : RHS_Su25SM_vvs_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_Su25_Cluster_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "Su-25 Cluster";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Pilot_Winter";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "TKA";

    };

    class I_Chernarus_L39_AA_Winter : I_Plane_Fighter_03_dynamicLoadout_F_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_L39_AA_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "L-39 AA";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Pilot_Winter";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "GREY";

    };

    class I_Chernarus_T55_Winter : LOP_AFR_T55_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_T55_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "T-55";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Crew_Winter";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Crew_Winter"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "ANA";

    };

    class I_Chernarus_T72_Winter : rhsgref_ins_g_t72bc_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_T72_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "T-72";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Pilot_Winter";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_Chernarus_Pilot_Winter"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "ANA";

    };

    class I_Chernarus_UAZ32_Closed_Winter : rhsgref_ins_uaz_OCimport_02 {
        editorPreview = "\x\addons\ichernaruswinter\data\preview\I_Chernarus_UAZ32_Closed_Winter.jpg";
        author = "Jebby";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-32 Closed";
        side = 2;
        faction = "I_Chernarus_Winter";
        crew = "I_Chernarus_Crew_Winter";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};
        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "White";

    };
};
