class CfgVehicles {
	class O_Soldier_F;
	class BNB_EX_Surpat_Gear_Uniform : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Rifleman";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_SS : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_SS";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Team Leader";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_SS";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_GP_Uniform : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_GP_Uniform";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Rifleman(GP)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_GP_Camo";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1_green_pants.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_GP_Uniform_SS : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_GP_Uniform_SS";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Team Leader(GP)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_GP_Camo_SS";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1_green_pants.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_GS_Uniform : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_GS_Uniform";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Rifleman(GS)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_GS_Camo";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1_green_shirt.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_GS_Uniform_SS : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_GS_Uniform_SS";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Team Leader(GS)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_GS_Camo_SS";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1_green_shirt.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_TP_Uniform : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_TP_Uniform";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Rifleman(TP)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_TP_Camo";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1_tan_pants.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_TP_Uniform_SS : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_TP_Uniform_SS";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Team Leader(TP)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_TP_Camo_SS";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1_tan_pants.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_TS_Uniform : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_TS_Uniform";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Rifleman(TS)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_TS_Camo";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1_tan_shirt.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_TS_Uniform_SS : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_TS_Uniform_SS";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Team Leader(TS)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_beta\INDEP\ia_soldier_02.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_TS_Camo_SS";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_1_tan_shirt.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_BDU : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_BDU";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Rifleman(BDU)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_BDU";
		hiddenSelections[] = {"Camo1","camo2","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_officer.paa","\x\bnb_ex\surpat_gear\data\surpat_1.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_BDU_GP : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_BDU_GP";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Rifleman(BDU GP)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_BDU_GP";
		hiddenSelections[] = {"Camo1","camo2","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_officer.paa","\x\bnb_ex\surpat_gear\data\surpat_1_green_pants.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_BDU_TP : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_BDU_TP";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Rifleman(BDU TP)";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\Characters_F_Beta\INDEP\ia_officer.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_BDU_TP";
		hiddenSelections[] = {"Camo1","camo2","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_officer.paa","\x\bnb_ex\surpat_gear\data\surpat_1_tan_pants.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_TShirt : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_TShirt";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Medic";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_f_gamma\Guerrilla\ig_guerrilla1_1.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_TShirt";
		hiddenSelections[] = {"Camo1","Camo2"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\moh_tshirt.paa","\x\bnb_ex\surpat_gear\data\surpat_1.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_Crye : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_Crye";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Operator";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_Crye";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_crye.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_Crye_TS : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_Crye_TS";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Operator TS";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_Crye_TS";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_crye_tan_shirt.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_Crye_TP : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_Crye_TP";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Operator TP";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_Crye_TP";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_crye_tan_pants.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_Crye_GP : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_Crye_GP";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Operator GP";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_Crye_GP";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_crye_green_pants.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_Crye_GS : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_Crye_GS";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Operator GS";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_Crye_GS";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_crye_green_shirt.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
	class BNB_EX_Surpat_Gear_Uniform_Crye_Tee : O_Soldier_F {
		author = "VanSchmoozin";
		_generalMacro = "BNB_EX_Surpat_Gear_Uniform_Crye_Tee";
		scope = 1;
		scopeCurator = 0;
		displayName = "SURPAT Lite";
		// identityTypes[] = {"Head_NATO","G_NATO_default"};
		// genericNames = "NATOMen";
		// faction = "BNB_EX_Surpat_Gear";
		model = "\A3\characters_F\BLUFOR\b_soldier_02.p3d";
		uniformClass = "BNB_EX_Surpat_Gear_Camo_Crye_Tee";
		hiddenSelections[] = {"Camo","Insignia"};
		hiddenSelectionsTextures[] = {"\x\bnb_ex\surpat_gear\data\surpat_crye.paa"};
		// weapons[] = {"Throw","Put"};
		// respawnWeapons[] = {"Throw","Put"};
		// magazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// respawnMagazines[] = {"HandGrenade","HandGrenade","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green"};
		// linkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
		// respawnLinkedItems[] = {"ItemMap","ItemCompass","ItemWatch","ItemRadio"};
	};
};
