//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 190.145381 on Stable branch
// Generated with ALiVE version 1.9.1.1901021
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_Norway {
        displayName = "Norwegian army";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\Norway_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Norway_ca.paa";
        priority = 0;
    };
};//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 190.145381 on Stable branch
// Generated with ALiVE version 1.9.1.1901021
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_Norway {
        displayName = "Norwegian army";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\Norway_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Norway_ca.paa";
        priority = 0;
    };
};//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 190.145381 on Stable branch
// Generated with ALiVE version 1.9.1.1901021
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_Norway {
        displayName = "Norwegian army";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\Norway_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Norway_ca.paa";
        priority = 0;
    };
};