class CfgPatches {
	class B_NorwayArmy {
		name = "2BNB Extras - Norway Units";
		units[] = {
			// Arctic
			"B_NorwayArmy_Man_Arctic",
			"B_NorwayArmy_Medic_Arctic",
			"B_NorwayArmy_LMG_762_Arctic",
			"B_NorwayArmy_LMG_556_Arctic",
			"B_NorwayArmy_Marksman_Arctic",
			"B_NorwayArmy_Engineer_EOD_Arctic",
			"B_NorwayArmy_1IC_Arctic",
			"B_NorwayArmy_2IC_Arctic",
			"B_NorwayArmy_Rifleman_AT_Arctic",
			"B_NorwayArmy_Rifleman_Arctic",
			"B_NorwayArmy_Crew_Arctic",
			"B_NorwayArmy_Pilot_Arctic",
			"B_NorwayArmy_Leopard_2SG_Arctic",
			"B_NorwayArmy_CV90_Veteran_Arctic",
			"B_NorwayArmy_CV90_Viking_Arctic",
			"B_NorwayArmy_Scania_Arctic",
			"B_NorwayArmy_Scania_Covered_Arctic",
			"B_NorwayArmy_Scania_Fuel_Arctic",
			"B_NorwayArmy_Scania_Utility_Arctic",
			"B_NorwayArmy_Scania_Medical_Arctic",
			"B_NorwayArmy_M113_Arctic",
			"B_NorwayArmy_M113_M2_Arctic",
			"B_NorwayArmy_M113_Medical_Arctic",
			"B_NorwayArmy_M113_M2_Shield_Arctic",
			"B_NorwayArmy_C130J_Arctic",
			"B_NorwayArmy_Bell412_Arctic",
			"B_NorwayArmy_Bell412_Armed_Arctic",
			"B_NorwayArmy_Recon_IC_Arctic",
			"B_NorwayArmy_Recon_Rifleman_Arctic",
			"B_NorwayArmy_Sniper_Arctic",
			"B_NorwayArmy_Spotter_Arctic",
			"B_NorwayArmy_Zeus_Arctic",

			// Desert
			"B_NorwayArmy_Man_Desert",
			"B_NorwayArmy_Medic_Desert",
			"B_NorwayArmy_LMG_762_Desert",
			"B_NorwayArmy_LMG_556_Desert",
			"B_NorwayArmy_Marksman_Desert",
			"B_NorwayArmy_Engineer_EOD_Desert",
			"B_NorwayArmy_1IC_Desert",
			"B_NorwayArmy_2IC_Desert",
			"B_NorwayArmy_Rifleman_AT_Desert",
			"B_NorwayArmy_Rifleman_Desert",
			"B_NorwayArmy_Crew_Desert",
			"B_NorwayArmy_Pilot_Desert",
			"B_NorwayArmy_Leopard_2SG_Desert",
			"B_NorwayArmy_CV90_Veteran_Desert",
			"B_NorwayArmy_CV90_Viking_Desert",
			"B_NorwayArmy_Scania_Desert",
			"B_NorwayArmy_Scania_Covered_Desert",
			"B_NorwayArmy_Scania_Fuel_Desert",
			"B_NorwayArmy_Scania_Utility_Desert",
			"B_NorwayArmy_Scania_Medical_Desert",
			"B_NorwayArmy_M113_Desert",
			"B_NorwayArmy_M113_M2_Desert",
			"B_NorwayArmy_M113_Medical_Desert",
			"B_NorwayArmy_M113_M2_Shield_Desert",
			"B_NorwayArmy_C130J_Desert",
			"B_NorwayArmy_Bell412_Desert",
			"B_NorwayArmy_Bell412_Armed_Desert",
			"B_NorwayArmy_Recon_IC_Desert",
			"B_NorwayArmy_Recon_Rifleman_Desert",
			"B_NorwayArmy_Sniper_Desert",
			"B_NorwayArmy_Spotter_Desert",
			"B_NorwayArmy_Zeus_Desert",

			// Multicam
			"B_NorwayArmy_Man_Multicam",
			"B_NorwayArmy_Medic_Multicam",
			"B_NorwayArmy_LMG_762_Multicam",
			"B_NorwayArmy_LMG_556_Multicam",
			"B_NorwayArmy_Marksman_Multicam",
			"B_NorwayArmy_Engineer_EOD_Multicam",
			"B_NorwayArmy_1IC_Multicam",
			"B_NorwayArmy_2IC_Multicam",
			"B_NorwayArmy_Rifleman_AT_Multicam",
			"B_NorwayArmy_Rifleman_Multicam",
			"B_NorwayArmy_Crew_Multicam",
			"B_NorwayArmy_Pilot_Multicam",
			"B_NorwayArmy_Recon_IC_Multicam",
			"B_NorwayArmy_Recon_Rifleman_Multicam",
			"B_NorwayArmy_Sniper_Multicam",
			"B_NorwayArmy_Spotter_Multicam",
			"B_NorwayArmy_Zeus_Multicam",

			// Woodland
			"B_NorwayArmy_Rifleman_Woodland",
			"B_NorwayArmy_Rifleman_AT_Woodland",
			"B_NorwayArmy_Engineer_EOD_Woodland",
			"B_NorwayArmy_1IC_Woodland",
			"B_NorwayArmy_2IC_Woodland",
			"B_NorwayArmy_Marksman_Woodland",
			"B_NorwayArmy_LMG_556_Woodland",
			"B_NorwayArmy_LMG_762_Woodland",
			"B_NorwayArmy_Medic_Woodland",
			"B_NorwayArmy_Man_Woodland",
			"B_NorwayArmy_Crew_Woodland",
			"B_NorwayArmy_Pilot_Woodland",
			"B_NorwayArmy_Recon_IC_Woodland",
			"B_NorwayArmy_Recon_Rifleman_Woodland",
			"B_NorwayArmy_Sniper_Woodland",
			"B_NorwayArmy_Spotter_Woodland",
			"B_NorwayArmy_Zeus_Woodland",

			"B_NorwayArmy_Command_Humvee_Woodland",
			"B_NorwayArmy_Armed_Humvee_M2_Woodland",
			"B_NorwayArmy_Armed_Humvee_Mk19_Woodland",
			"B_NorwayArmy_HEMTT_Ammo_Woodland",
			"B_NorwayArmy_HEMTT_Fuel_Woodland",
			"B_NorwayArmy_HEMTT_Repair_Woodland",
			"B_NorwayArmy_Hunter_M2_Woodland",
			"B_NorwayArmy_Stryker_Woodland",
			"B_NorwayArmy_M113_Woodland",
			"B_NorwayArmy_M113_M2_Woodland",
			"B_NorwayArmy_M113_Medical_Woodland",
			"B_NorwayArmy_M113_M2_Shield_Woodland",
			"B_NorwayArmy_Leopard_2SG_Kompis_Woodland",
			"B_NorwayArmy_Leopard_2SG_Woodland",
			"B_NorwayArmy_CV90_Veteran_Woodland",
			"B_NorwayArmy_CV90_Viking_Woodland",
			"B_NorwayArmy_Scania_Woodland",
			"B_NorwayArmy_Scania_Covered_Woodland",
			"B_NorwayArmy_Scania_Fuel_Woodland",
			"B_NorwayArmy_Scania_Utility_Woodland",
			"B_NorwayArmy_Scania_Medical_Woodland",
			"B_NorwayArmy_Huey_Gunship_Woodland",
			"B_NorwayArmy_Huey_Transport_Woodland",
			"B_NorwayArmy_Blackhawk_Woodland",
			"B_NorwayArmy_Littlebird_CAS_Woodland",
			"B_NorwayArmy_C130J_Woodland",
			"B_NorwayArmy_Bell412_Woodland",
			"B_NorwayArmy_Bell412_Armed_Woodland",
			"B_NorwayArmy_JAS_39_Gripen_Woodland",
			"B_NorwayArmy_Static_MG_High_Woodland",
			"B_NorwayArmy_Static_MG_Low_Woodland",
			"B_NorwayArmy_Mortar_Woodland",
			"B_NorwayArmy_Static_GMG_Woodland",
			"B_NorwayArmy_Static_TOW_Woodland",
			"B_NorwayArmy_A10_Woodland"
		};
		weapons[] = {};
		requiredVersion = 1.62;
		requiredAddons[] = {
			"A3_Armor_F_EPB_APC_Tracked_03",
			"A3_Armor_F_EPB_MBT_03",
			"rhs_c_mig29",
			"A3_Air_F_EPC_Plane_CAS_01"
		};
		author = "2nd Battalion, Nord Brigade";
		authors[] = {
			"D. Ford",
			"Arend",
			"Jebby",
			"Ezpez",
			"Christiansen [NTF]"
		};
	};
};
