//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 190.145381 on Stable branch
// Generated with ALiVE version 1.9.1.1901021
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

	class B_Soldier_TL_F;
	class B_Soldier_TL_F_OCimport_01 : B_Soldier_TL_F { scope = 0; class EventHandlers; };
	class B_Soldier_TL_F_OCimport_02 : B_Soldier_TL_F_OCimport_01 { class EventHandlers; };


	class B_Norway_IC_2IC_01 : B_Soldier_TL_F_OCimport_02 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "M81 IC/2IC ";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_M81_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_anprc152","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_anprc152","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK416GL","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK416GL","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell","rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell","rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell"};

		backpack = "tfw_ilbe_gr";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK416GL","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552_3XDOWN",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{"1Rnd_SmokeRed_Grenade_shell",1},""},{},{},{"VSM_M81_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_M81",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",5,30}}},{"tfw_ilbe_gr",{{"ACE_30Rnd_556x45_Stanag_Mk262_mag",6,30},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",3,1},{"SmokeShell",5,1},{"CUP_1Rnd_HE_M203",10,1},{"1Rnd_Smoke_Grenade_shell",5,1},{"1Rnd_SmokeRed_Grenade_shell",4,1},{"SmokeShellOrange",2,1},{"SmokeShellPurple",2,1},{"SmokeShellRed",2,1},{"SmokeShellYellow",2,1}}},"VSM_Mich2000_2_M81","",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_anprc152","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_M81_AT_01 : B_Norway_IC_2IC_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "M81 AT";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_M81_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK416CUSTOMvfgB","launch_MRAWS_green_rail_F","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK416CUSTOMvfgB","launch_MRAWS_green_rail_F","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","MRAWS_HEAT_F","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","MRAWS_HEAT_F","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		backpack = "VSM_M81_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{"launch_MRAWS_green_rail_F","","","",{"MRAWS_HEAT_F",1},{},""},{},{"VSM_M81_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_M81",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30}}},{"VSM_M81_Backpack_Kitbag",{{"ACE_30Rnd_556x45_Stanag_Mk262_mag",4,30},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1},{"MRAWS_HEAT_F",3,1}}},"VSM_Mich2000_2_M81","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_M81_LMG_01 : B_Norway_IC_2IC_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "M81 LMG";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_M81_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"CUP_lmg_MG3_rail","ACE_VectorDay"};
		respawnWeapons[] = {"CUP_lmg_MG3_rail","ACE_VectorDay"};

		magazines[] = {"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};
		respawnMagazines[] = {"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};

		backpack = "VSM_M81_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_MG3_rail","","","CUP_optic_HoloBlack",{"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",120},{},""},{},{},{"VSM_M81_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_M81",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5}}},{"VSM_M81_Backpack_Kitbag",{{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1},{"CUP_120Rnd_TE4_LRT4_Green_Tracer_762x51_Belt_M",3,120}}},"VSM_Mich2000_2_M81","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_M81_Marksman_01 : B_Norway_IC_2IC_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "M81 Marksman";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_M81_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK417_16in","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK417_16in","ACE_VectorDay"};

		magazines[] = {"SMA_20Rnd_762x51mm_M80A1_EPR_IR","SMA_20Rnd_762x51mm_M80A1_EPR_IR"};
		respawnMagazines[] = {"SMA_20Rnd_762x51mm_M80A1_EPR_IR","SMA_20Rnd_762x51mm_M80A1_EPR_IR"};

		backpack = "VSM_M81_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK417_16in","","SMA_SFPEQ_HK417TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",{"SMA_20Rnd_762x51mm_M80A1_EPR_IR",20},{},"bipod_01_F_blk"},{},{},{"VSM_M81_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_M81",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"SMA_20Rnd_762x51mm_M80A1_EPR_IR",7,20}}},{"VSM_M81_Backpack_Kitbag",{{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1},{"SMA_20Rnd_762x51mm_M80A1_EPR_IR",7,20},{"20Rnd_762x51_Mag",7,20}}},"VSM_Mich2000_2_M81","G_Tactical_Clear",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_M81_Rifleman_01 : B_Norway_IC_2IC_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "M81 Rifleman";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_M81_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK416CUSTOMvfgB","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK416CUSTOMvfgB","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		backpack = "VSM_M81_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"VSM_M81_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_M81",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5}}},{"VSM_M81_Backpack_Kitbag",{{"ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",8,30},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1}}},"VSM_Mich2000_2_M81","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_M81_Medic_01 : B_Norway_M81_Rifleman_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "M81 Medic";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_M81_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_M81","VSM_Mich2000_2_M81","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK416CUSTOMvfgB","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK416CUSTOMvfgB","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		backpack = "VSM_M81_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"VSM_M81_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"ACE_bloodIV_250",3},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_M81",{{"ACE_fieldDressing",25},{"ACE_elasticBandage",51},{"ACE_quikclot",30},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",14},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",31},{"ACE_tourniquet",5},{"ACE_morphine",15},{"ACE_bloodIV",1}}},{"VSM_M81_Backpack_Kitbag",{{"ACE_tourniquet",4},{"ACE_bloodIV_500",11},{"ACE_surgicalKit",1},{"ACE_quikclot",10},{"ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",8,30},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1}}},"VSM_Mich2000_2_M81","VSM_Balaclava2_OD_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_AOR1_IC_2IC_01 : B_Norway_IC_2IC_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "AOR1 IC/2IC";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_AOR1_Crye_SS_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK416GL","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK416GL","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell","rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell","rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell"};

		backpack = "tfw_ilbe_dd_d";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK416GL","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552_3XDOWN",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{"1Rnd_SmokeRed_Grenade_shell",1},""},{},{},{"VSM_AOR1_Crye_SS_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_AOR1",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",5,30}}},{"tfw_ilbe_dd_d",{{"ACE_30Rnd_556x45_Stanag_Mk262_mag",6,30},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",3,1},{"SmokeShell",5,1},{"CUP_1Rnd_HE_M203",10,1},{"1Rnd_Smoke_Grenade_shell",5,1},{"1Rnd_SmokeRed_Grenade_shell",4,1},{"SmokeShellOrange",2,1},{"SmokeShellPurple",2,1},{"SmokeShellRed",2,1},{"SmokeShellYellow",2,1}}},"VSM_Mich2000_2_aor1","G_Combat",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_AOR1_AT_01 : B_Norway_M81_AT_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "AOR1 AT";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_AOR1_Crye_SS_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK416CUSTOMvfgB","launch_MRAWS_sand_rail_F","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK416CUSTOMvfgB","launch_MRAWS_sand_rail_F","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","MRAWS_HEAT_F","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","MRAWS_HEAT_F","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		backpack = "VSM_AOR1_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{"launch_MRAWS_sand_rail_F","","","",{"MRAWS_HEAT_F",1},{},""},{},{"VSM_AOR1_Crye_SS_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_AOR1",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30}}},{"VSM_AOR1_Backpack_Kitbag",{{"ACE_30Rnd_556x45_Stanag_Mk262_mag",4,30},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1}}},"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_tan_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_AOR1_Marksman_01 : B_Norway_M81_Marksman_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "AOR1 Marksman";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_AOR1_Crye_SS_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK417_16in","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK417_16in","ACE_VectorDay"};

		magazines[] = {"SMA_20Rnd_762x51mm_M80A1_EPR_IR","SMA_20Rnd_762x51mm_M80A1_EPR_IR"};
		respawnMagazines[] = {"SMA_20Rnd_762x51mm_M80A1_EPR_IR","SMA_20Rnd_762x51mm_M80A1_EPR_IR"};

		backpack = "VSM_AOR1_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK417_16in","","SMA_SFPEQ_HK417TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",{"SMA_20Rnd_762x51mm_M80A1_EPR_IR",20},{},"bipod_01_F_blk"},{},{},{"VSM_AOR1_Crye_SS_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_AOR1",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"SMA_20Rnd_762x51mm_M80A1_EPR_IR",7,20}}},{"VSM_AOR1_Backpack_Kitbag",{{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1},{"SMA_20Rnd_762x51mm_M80A1_EPR_IR",7,20},{"20Rnd_762x51_Mag",7,20}}},"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_tan_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_AOR1_Rifleman_01 : B_Norway_M81_Rifleman_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "AOR1 Rifleman";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_AOR1_Crye_SS_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK416CUSTOMvfgB","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK416CUSTOMvfgB","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		backpack = "VSM_AOR1_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"VSM_AOR1_Crye_SS_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_AOR1",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5}}},{"VSM_AOR1_Backpack_Kitbag",{{"ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",8,30},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1}}},"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_tan_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_AOR1_Medic_01 : B_Norway_M81_Medic_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "AOR1 Medic";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_AOR1_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_HK416CUSTOMvfgB","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_HK416CUSTOMvfgB","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		backpack = "VSM_AOR1_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"SMA_HK416CUSTOMvfgB","","SMA_SFPEQ_HKTOP_BLK","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"VSM_AOR1_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"ACE_bloodIV_250",3},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_AOR1",{{"ACE_fieldDressing",25},{"ACE_elasticBandage",51},{"ACE_quikclot",30},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",14},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",31},{"ACE_tourniquet",5},{"ACE_morphine",15},{"ACE_bloodIV",1}}},{"VSM_AOR1_Backpack_Kitbag",{{"ACE_tourniquet",4},{"ACE_bloodIV_500",11},{"ACE_surgicalKit",1},{"ACE_quikclot",10},{"ACE_30Rnd_556x45_Stanag_Mk318_mag",10,30},{"ACE_30Rnd_556x45_Stanag_Mk262_mag",8,30},{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1}}},"VSM_Mich2000_2_aor1","VSM_Facemask_tan_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_AOR_LMG_01 : B_Norway_M81_LMG_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "AOR LMG";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_AOR1_Crye_SS_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_AOR1","VSM_Mich2000_2_aor1","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"CUP_lmg_MG3_rail","ACE_VectorDay"};
		respawnWeapons[] = {"CUP_lmg_MG3_rail","ACE_VectorDay"};

		magazines[] = {"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};
		respawnMagazines[] = {"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};

		backpack = "VSM_AOR1_Backpack_Kitbag";

		ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_MG3_rail","","","CUP_optic_HoloBlack",{"CUP_120Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",120},{},""},{},{},{"VSM_AOR1_Crye_SS_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_AOR1",{{"ACE_fieldDressing",4},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5}}},{"VSM_AOR1_Backpack_Kitbag",{{"SmokeShellBlue",2,1},{"SmokeShellGreen",2,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",4,1},{"CUP_120Rnd_TE4_LRT4_Green_Tracer_762x51_Belt_M",3,120}}},"VSM_Mich2000_2_aor1","VSM_Shemagh_Balaclava2_OD_Peltor_Goggles",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_M81_Crew_01 : B_Norway_M81_Rifleman_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "M81 Crew";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_M81_Camo";

		linkedItems[] = {"VSM_FAPC_Operator_M81","CUP_H_CZ_Helmet05","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_FAPC_Operator_M81","CUP_H_CZ_Helmet05","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_CTAROD_F","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_CTAROD_F","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		ALiVE_orbatCreator_loadout[] = {{"SMA_CTAROD_F","","","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"VSM_M81_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_FAPC_Operator_M81",{{"ACE_fieldDressing",8},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"ACE_bloodIV_500",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30}}},{},"CUP_H_CZ_Helmet05","VSM_Shemagh_Balaclava2_tan_Peltor_Glasses",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_M81_Air_Crew_01 : B_Norway_M81_Crew_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "M81 Air Crew";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_M81_Camo";

		linkedItems[] = {"VSM_RAV_operator_M81","rhsusf_hgu56p_visor_green","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_RAV_operator_M81","rhsusf_hgu56p_visor_green","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_CTAROD_F","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_CTAROD_F","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		ALiVE_orbatCreator_loadout[] = {{"SMA_CTAROD_F","","","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"VSM_M81_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_RAV_operator_M81",{{"ACE_fieldDressing",8},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"ACE_bloodIV_500",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag",5,30}}},{},"rhsusf_hgu56p_visor_green","G_Tactical_Clear",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_AOR1_Crew_01 : B_Norway_M81_Crew_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "AOR1 Crew";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_AOR1_Camo";

		linkedItems[] = {"VSM_RAV_operator_AOR1","rhsusf_opscore_aor1_pelt_nsw","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter"};
		respawnlinkedItems[] = {"VSM_RAV_operator_AOR1","rhsusf_opscore_aor1_pelt_nsw","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter"};

		weapons[] = {"SMA_CTAR_F","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_CTAR_F","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		ALiVE_orbatCreator_loadout[] = {{"SMA_CTAR_F","","","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"VSM_AOR1_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_RAV_operator_AOR1",{{"ACE_fieldDressing",8},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"ACE_bloodIV_500",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag",3,30}}},{},"rhsusf_opscore_aor1_pelt_nsw","G_Tactical_Black",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter",""}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

	class B_Norway_AOR1_Air_Crew_01 : B_Norway_AOR1_Crew_01 {
		author = "Maj. D. Ford";
		scope = 2;
		scopeCurator = 2;
		displayName = "AOR1 Air Crew";
		side = 1;
		faction = "B_Norway";

		identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

		uniformClass = "VSM_AOR1_Camo";

		linkedItems[] = {"VSM_RAV_operator_AOR1","rhsusf_hgu56p_visor_black","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};
		respawnlinkedItems[] = {"VSM_RAV_operator_AOR1","rhsusf_hgu56p_visor_black","ItemMap","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"};

		weapons[] = {"SMA_CTAR_F","ACE_VectorDay"};
		respawnWeapons[] = {"SMA_CTAR_F","ACE_VectorDay"};

		magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
		respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

		ALiVE_orbatCreator_loadout[] = {{"SMA_CTAR_F","","","SMA_eotech552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"VSM_AOR1_Camo",{{"ACE_fieldDressing",4},{"ACE_packingBandage",2},{"ACE_morphine",2},{"ACE_tourniquet",2},{"HandGrenade",2,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1}}},{"VSM_RAV_operator_AOR1",{{"ACE_fieldDressing",8},{"ACE_elasticBandage",7},{"ACE_quikclot",7},{"ACE_CableTie",3},{"ACE_EarPlugs",1},{"ACE_EntrenchingTool",1},{"ACE_epinephrine",4},{"ACE_IR_Strobe_Item",2},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_packingBandage",9},{"ACE_tourniquet",5},{"ACE_morphine",5},{"ACE_bloodIV_500",1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag",3,30}}},{},"rhsusf_hgu56p_visor_black","",{"ACE_VectorDay","","","",{},{},""},{"ItemMap","","TFAR_rf7800str","ItemCompass","ACE_Altimeter","A3_GPNVG18_F"}};


		class EventHandlers : EventHandlers {
			class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

			class ALiVE_orbatCreator {
				init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, '_2BNB'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
			};

		};

		// custom attributes (do not delete)
		ALiVE_orbatCreator_owned = 1;
		ALiVE_orbatCreator_insignia = "_2BNB";

	};

};
